### ISSUE TITLE
Update docker image to include pciutils

### ISSUE THREAD

**Issue by bbradelTT** [tenstorrent/tt-metal#11462]
I recently tried to reset a board via tt-smi and got the following errors:
```
/home/software/syseng/gs/tt-smi -tr all
Traceback (most recent call last):
  File "tt_tools/common/api.py", line 413, in __init__
  File "tt_tools/common/api.py", line 443, in detect_chips
  File "subprocess.py", line 512, in run
subprocess.CalledProcessError: Command 'lspci -d 1e52: -n' returned non-zero exit status 127.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tt_smi.py", line 418, in <module>
  File "tt_smi.py", line 290, in main
  File "tt_tools/common/api.py", line 436, in __init__
tenstorrent.tenstorrent.TTError: Failed to initialize TTHost.
[2149502] Failed to execute script 'tt_smi' due to unhandled exception!
```

The fix was to install pciutils:
```
sudo apt-get update
sudo apt install pciutils
```

That package should be included in the docker image.

At least
[ghcr.io/tenstorrent/tt-metal/tt-metalium/ubuntu-20.04-amd64:latest](http://ghcr.io/tenstorrent/tt-metal/tt-metalium/ubuntu-20.04-amd64:latest)

cc @ttmchiou @TT-billteng

**Comment by bbradelTT** [comment]
One note is that we currently have to use 20.04 not 22.04 on IRD

**Comment by ttmchiou** [comment]
this has already been added into dockerfile
