### ISSUE TITLE
[Bug Report] Enviroment create by create_venv.sh fails to initialize PyTorch

### ISSUE THREAD

**Issue by marty1885** [tenstorrent/tt-metal#11581]
**Describe the bug**
Currently a completely new environment created by `create_venv.sh` will install numpy 2.0. However the installed torch 2.1.0 is not compatible with it. Leading the the following error upon `import ttnn`.

```
Python 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ttnn
2024-08-17 00:03:14.053 | DEBUG    | ttnn:<module>:82 - Initial ttnn.CONFIG:
Config{cache_path=/home/marty/.cache/ttnn,model_cache_path=/home/marty/.cache/ttnn/models,tmp_dir=/tmp/ttnn,enable_model_cache=false,enable_fast_runtime_mode=true,throw_exception_on_fallback=false,enable_logging=false,enable_graph_report=false,enable_detailed_buffer_report=false,enable_detailed_tensor_report=false,enable_comparison_mode=false,comparison_mode_pcc=0.9999,root_report_path=generated/ttnn/reports,report_name=std::nullopt,std::nullopt}

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<stdin>", line 1, in <module>
  File "/home/marty/Documents/tt-metal/ttnn/ttnn/__init__.py", line 229, in <module>
    import ttnn.operations
  File "/home/marty/Documents/tt-metal/ttnn/ttnn/operations/__init__.py", line 11, in <module>
    _module = loader.find_spec(module_name).loader.load_module(module_name)
  File "/home/marty/Documents/tt-metal/ttnn/ttnn/operations/binary_backward.py", line 8, in <module>
    from ttnn.operations.complex_binary_backward import (
  File "/home/marty/Documents/tt-metal/ttnn/ttnn/operations/complex_binary_backward.py", line 6, in <module>
    import torch
  File "/home/marty/Documents/tt-metal/python_env/lib/python3.10/site-packages/torch/__init__.py", line 1477, in <module>
    from .functional import *  # noqa: F403
  File "/home/marty/Documents/tt-metal/python_env/lib/python3.10/site-packages/torch/functional.py", line 9, in <module>
    import torch.nn.functional as F
  File "/home/marty/Documents/tt-metal/python_env/lib/python3.10/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/home/marty/Documents/tt-metal/python_env/lib/python3.10/site-packages/torch/nn/modules/__init__.py", line 35, in <module>
    from .transformer import TransformerEncoder, TransformerDecoder, \
  File "/home/marty/Documents/tt-metal/python_env/lib/python3.10/site-packages/torch/nn/modules/transformer.py", line 20, in <module>
    device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
/home/marty/Documents/tt-metal/python_env/lib/python3.10/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),

```

**To Reproduce**
1. Delete existing environment
2. Create a new one using create_venv,sh
3. Activate the environment
4. Run python and enter `import ttnn`
5. See error

**Expected behavior**
Torch should not fail to install

**Screenshots**

**Please complete the following environment information:**
- OS: Ubuntu 22.04
- Commit: fd4691f9469aecd08c3db921f130039841a778f4

**Additional context**
If failing to create a new env. Please see [my workaround](https://github.com/tenstorrent/tt-metal/issues/11144#issuecomment-2294735180)

**Comment by dongjin-na** [comment]
Here is the following workaround:
1. Numpy Compatibility Issue:
During the initial setup, there was an error related to the version of numpy. This was resolved by downgrading the numpy package as follows:
```bash
pip install "numpy<2"
```

2. Issue with ttnn Import in Pytest:
While importing torch in the Python shell worked fine, running tests with pytest resulted in an import error:
```python
E   ImportError: cannot import name 'ConcatMeshToTensor' from 'ttnn' (unknown location)
```
To resolve this, I un-commented the previously commented section in the create_venv.sh script and ran it again, which downgraded the pip version:
```bash
echo "Forcefully using a version of pip that will work with our view of editable installs"
pip install --force-reinstall pip==20.1.1
```

**Comment by TT-billteng** [comment]
will look into this today

**Comment by tt-rkim** [comment]
https://github.com/tenstorrent/tt-metal/issues/11144#issuecomment-2318184316

**Comment by marty1885** [comment]
@tt-rkim for this PR. I think it's a different problem then the pip one. Can we simply add `numpy<2` to the requirements and close this issue?

**Comment by tt-rkim** [comment]
Can we close this @marty1885 ? It's now on main.
Pls check

**Comment by marty1885** [comment]
Thanks. Closing
