### ISSUE TITLE
[Bug Report] Hang on basic TTNN program exit

### ISSUE THREAD

**Issue by marty1885** [tenstorrent/tt-metal#11639]
**Describe the bug**

The following Python program hangs on exit and using an entire CPU core. Note that any operations causes hang on exit. Including add, subtract. Not just transpose

```python
import ttnn
from tt_lib import tensor
device = ttnn.open_device(0)

shape = (1, 1, 32, 32)
x = ttnn.to_device(ttnn.to_layout(ttnn.zeros(shape), ttnn.TILE_LAYOUT), device)
y = ttnn.transpose(x, 0 ,2)
print(y.shape)
ttnn.close_device(device)
```

This is the stack trace from GDB during the hang.

```
__futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x55555a413898) at ./nptl/futex-internal.c:57
57	./nptl/futex-internal.c: No such file or directory.
(gdb) bt
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x55555a413898)
    at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (cancel=true, private=0, abstime=0x0, clockid=0, expected=0, futex_word=0x55555a413898)
    at ./nptl/futex-internal.c:87
#2  __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x55555a413898, expected=expected@entry=0, 
    clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at ./nptl/futex-internal.c:139
#3  0x00007ffff7c93a41 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x55555a4138a0, cond=0x55555a413870)
    at ./nptl/pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x55555a413870, mutex=0x55555a4138a0) at ./nptl/pthread_cond_wait.c:627
#5  0x00007ffff382e403 in std::condition_variable::wait<tt::tt_metal::HWCommandQueue::finish()::<lambda()> > (__p=..., __lock=..., 
    this=0x55555a413870) at /usr/include/c++/13/condition_variable:105
#6  tt::tt_metal::HWCommandQueue::finish (this=0x55555a3e3720)
    at /home/marty/Documents/tt-metal/tt_metal/impl/dispatch/command_queue.cpp:2470
#7  0x00007ffff3840f33 in tt::tt_metal::CommandQueue::run_command_impl (this=0x55555a413aa0, command=...)
    at /home/marty/Documents/tt-metal/tt_metal/impl/dispatch/command_queue.cpp:3067
#8  0x00007ffff3843498 in tt::tt_metal::Finish (cq=...)
    at /home/marty/Documents/tt-metal/tt_metal/impl/dispatch/command_queue.cpp:2838
#9  0x00007ffff367f6c7 in tt::tt_metal::Synchronize (cq_id=..., device=<optimized out>)
    at /home/marty/Documents/tt-metal/tt_metal/tt_metal.cpp:1102
#10 tt::tt_metal::Synchronize (device=0x55555a38b8e0, cq_id=<optimized out>)
    at /home/marty/Documents/tt-metal/tt_metal/tt_metal.cpp:1096
#11 0x00007ffff5deb647 in operator() (__closure=<optimized out>, cq_id=..., device=<optimized out>)
    at /home/marty/Documents/tt-metal/ttnn/cpp/ttnn/deprecated/tt_lib/csrc/tt_lib_bindings.cpp:211
#12 pybind11::detail::argument_loader<tt::tt_metal::Device*, std::optional<unsigned char> >::call_impl<void, tt::tt_metal::DeviceModule(pybind11::module&)::<lambda(tt::tt_metal::Device*, std::optional<unsigned char>)>&, 0, 1, pybind11::detail::void_type> (f=..., 
    this=<optimized out>) at /home/marty/Documents/tt-metal/tt_metal/third_party/pybind11/include/pybind11/cast.h:1443
#13 pybind11::detail::argument_loader<tt::tt_metal::Device*, std::optional<unsigned char> >::call<void, pybind11::detail::void_type, tt--Type <RET> for more, q to quit, c to continue without paging--
::tt_metal::DeviceModule(pybind11::module&)::<lambda(tt::tt_metal::Device*, std::optional<unsigned char>)>&> (f=..., 
    this=<optimized out>) at /home/marty/Documents/tt-metal/tt_metal/third_party/pybind11/include/pybind11/cast.h:1417
#14 operator() (__closure=<optimized out>, call=...)
    at /home/marty/Documents/tt-metal/tt_metal/third_party/pybind11/include/pybind11/pybind11.h:248
#15 _FUN () at /home/marty/Documents/tt-metal/tt_metal/third_party/pybind11/include/pybind11/pybind11.h:223
#16 0x00007ffff407384e in pybind11::cpp_function::dispatcher (self=0x55555a413898, args_in=0x7fffc2bc9980, kwargs_in=0x0)
    at /home/marty/Documents/tt-metal/tt_metal/third_party/pybind11/include/pybind11/pybind11.h:939
#17 0x00005555556aedae in ?? ()
#18 0x00005555556a552b in _PyObject_MakeTpCall ()
#19 0x000055555569e16b in _PyEval_EvalFrameDefault ()
#20 0x00005555556af6ac in _PyFunction_Vectorcall ()
#21 0x0000555555697935 in _PyEval_EvalFrameDefault ()
#22 0x00005555556af6ac in _PyFunction_Vectorcall ()
#23 0x000055555569d742 in _PyEval_EvalFrameDefault ()
#24 0x0000555555694096 in ?? ()
#25 0x0000555555789f66 in PyEval_EvalCode ()
#26 0x00005555557b4e98 in ?? ()
#27 0x00005555557ae79b in ?? ()
#28 0x00005555557b4be5 in ?? ()
#29 0x00005555557b40c8 in _PyRun_SimpleFileObject ()
#30 0x00005555557b3d13 in _PyRun_AnyFileObject ()
#31 0x00005555557a670e in Py_RunMain ()
#32 0x000055555577cdfd in Py_BytesMain ()
#33 0x00007ffff7c29d90 in __libc_start_call_main (main=main@entry=0x55555577cdc0, argc=argc@entry=2, argv=argv@entry=0x7fffffffe228)
    at ../sysdeps/nptl/libc_start_call_main.h:58
#34 0x00007ffff7c29e40 in __libc_start_main_impl (main=0x55555577cdc0, argc=2, argv=0x7fffffffe228, init=<optimized out>, 
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe218) at ../csu/libc-start.c:392
--Type <RET> for more, q to quit, c to continue without paging--
```

But this is fine

```python
 import ttnn
 from tt_lib import tensor
 device = ttnn.open_device(0)
 
 shape = (1, 1, 32, 32)
 x = ttnn.to_device(ttnn.to_layout(ttnn.zeros(shape), ttnn.TILE_LAYOUT), device)
 ttnn.close_device(device)
```

The same issue occurs if I modify the [2nd example program](https://docs.tenstorrent.com/ttnn/latest/ttnn/usage.html#running-an-operation-on-the-device) to add instead of exp.

```python
import torch
import ttnn

device_id = 0
device = ttnn.open_device(device_id=device_id)

torch_input_tensor = torch.rand(2, 4, dtype=torch.float32)
input_tensor = ttnn.from_torch(torch_input_tensor, dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=device)
output_tensor = input_tensor + input_tensor # CHANGED HERE. CAUSES HANG
torch_output_tensor = ttnn.to_torch(output_tensor)

ttnn.close_device(device)
```

**To Reproduce**
1. Run the provided python script
2. Observe the hang

This recording shows what I'm experiencing.
https://asciinema.org/a/IA63ZykNPfERVLo3umlTlUQEi

**Expected behavior**
Program exit normally without hang

**Screenshots**

**Please complete the following environment information:**
- OS: Ubuntu 22.04
- Commit: 046237fd9c24f51fefd05f66c270c78e606eae85
- Compiler: GCC 13
- Card: e150

**Additional context**

**Comment by ayerofieiev-tt** [comment]
@tt-asaigal looks like a hang related to command queue. Can you please take a look?

cc @dmakoviichuk-tt

**Comment by tt-asaigal** [comment]
Hey @marty1885, thanks for filing the issue :) I ran all three tests locally on an e150 and they exit without a hang.

Looking at the backtrace of the test, it seems like the device hung during execution. Are there any specific environment variables that are being set prior to the test? Also wanted to make sure that the machine was in a good state before the tests were run.

**Comment by marty1885** [comment]
@tt-asaigal Ahhh you are right.. It seems my card can hang after a cold reboot randomly. Is it possible it is broken?

**Comment by tt-asaigal** [comment]
@marty1885 I'm not certain if this is an issue with the card itself. I've seen rare issues after a cold-boot, that could put the system in a bad state. 
@ayerofieiev-tt and I can internally redirect this to our systems engineering team, who would be better equipped to get to the bottom of this.

**Comment by marty1885** [comment]
Gotchain. Thanks for the timely help! Closing the issue for now. Feel free to reopen if any of the team members see fit
