### ISSUE TITLE
Sweeps: If external types move, the generation will not pickup on the changes to the tests

### ISSUE THREAD

**Issue by jdesousa-TT** [tenstorrent/tt-metal#12532]
- When refactoring on ttnn is done where the types do not change and remain equal, but the paths change (surfaces a lot in tt_lib refactor) the generation will not see any changes to the vectors, and cause the runner to fail
- This is because the vector equality check is happened on the unserialized vector, instead of the serialized representation.

e.g.
```
python tests/sweep_framework/runner.py --module-name matmul.full.matmul_default_block_sharded --vector-id NMJx3JEBwvAQT7JmF0zc
...
SWEEPS: Opened device configuration, default.
Traceback (most recent call last):
  File "tests/sweep_framework/runner.py", line 415, in <module>
    run_sweeps(args.module_name, args.suite_name, args.vector_id)
  File "tests/sweep_framework/runner.py", line 278, in run_sweeps
    results = execute_suite(test_module, test_vectors, pbar_manager, "Single Vector")
  File "tests/sweep_framework/runner.py", line 124, in execute_suite
    run(test_module, input_queue, output_queue)
  File "tests/sweep_framework/runner.py", line 57, in run
    test_vector = deserialize_vector(test_vector)
  File "/localdev/bbradel/tt-metal/tests/sweep_framework/serialize.py", line 36, in deserialize_vector
    test_vector = [deserialize(test_vector[elem]) for elem in test_vector]
  File "/localdev/bbradel/tt-metal/tests/sweep_framework/serialize.py", line 36, in <listcomp>
    test_vector = [deserialize(test_vector[elem]) for elem in test_vector]
  File "/localdev/bbradel/tt-metal/tests/sweep_framework/serialize.py", line 25, in deserialize
    type = eval(object["type"])
  File "<string>", line 1, in <module>
AttributeError: module 'ttnn._ttnn.deprecated' has no attribute 'tensor'
```

cc: @bbradelTT

**Comment by bbradelTT** [comment]
Thanks @jdesousa-TT
