### ISSUE TITLE
misc/test_binary_eq_int.py mismatch

### ISSUE THREAD

**Issue by eyonland** [tenstorrent/tt-metal#12574]
This test makes no sense to me at all.  We need to look at the intent of this test and see how it relates to binary eq here.  The test needs to be updated to better capture the intent and also updated to work on blackhole.

**Comment by ruthreshx** [comment]
Hi @eyonland ,
Since the test got aborted,  debugging through gdb args through the functional call..

```
Thread 39 "python3" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fff3d7fa700 (LWP 155183)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7deb859 in __GI_abort () at abort.c:79
#2  0x00007fffb361440b in ?? () from /lib/x86_64-linux-gnu/libc++abi.so.1
#3  0x00007fffb35fe03d in ?? () from /lib/x86_64-linux-gnu/libc++abi.so.1
#4  0x00007fffb3613573 in ?? () from /lib/x86_64-linux-gnu/libc++abi.so.1
#5  0x00007fffb3616346 in ?? () from /lib/x86_64-linux-gnu/libc++abi.so.1
#6  0x00007fffb36162cc in __cxa_throw () from /lib/x86_64-linux-gnu/libc++abi.so.1
#7  0x00007fffb43c89c6 in void tt::assert::tt_throw_impl<fmt::v11::basic_format_string<char> >(char const*, int, char const*, char const*, fmt::v11::basic_format_string<char> const&) () from /home/ubuntu/tt-metal/ttnn/ttnn/_ttnn.so
#8  0x00007fffb43c68a8 in void tt::assert::tt_throw<>(char const*, int, char const*, char const*, fmt::v11::basic_format_string<char>) ()
   from /home/ubuntu/tt-metal/ttnn/ttnn/_ttnn.so
#9  0x00007fffb3edf388 in tt::get_single_pack_src_format(tt::DataFormat, tt::DataFormat, tt::DataFormat, bool, bool, tt::ARCH) ()
   from /home/ubuntu/tt-metal/build_Release/lib/libtt_metal.so
#10 0x00007fffb3edf513 in tt::get_pack_src_formats(tt::DataFormat*, tt::DataFormat*, tt::DataFormat*, tt::DataFormat*, tt::DataFormat, bool, bool, tt::ARCH)
    () from /home/ubuntu/tt-metal/build_Release/lib/libtt_metal.so
#11 0x00007fffb3eec44d in void* std::__1::__thread_proxy[abi:ue170006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, tt::tt_metal::jit_build_genfiles_descriptors(tt::tt_metal::JitBuildEnv const&, tt::tt_metal::JitBuildOptions&)::$_0> >(void*)
    () from /home/ubuntu/tt-metal/build_Release/lib/libtt_metal.so
#12 0x00007ffff7dae609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#13 0x00007ffff7ee8353 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by ruthreshx** [comment]
Hi @eyonland ,
Since the issue thrown only on the GS device, hence we closing the ticket and test has been skipped for the GS device.
