### ISSUE TITLE
TTNN Matmul op doesn't broadcast batch dim of input a

### ISSUE THREAD

**Issue by sdjordjevicTT** [tenstorrent/tt-metal#12834]
**Describe the bug**
TTNN Matmul op does not work when the batch dim of input_tensor_a needs to be broadcasted. According to the [public documentation](https://docs.tenstorrent.com/ttnn/latest/ttnn/ttnn/matmul.html), this kind of product is supported. I am consistently encountering an error when trying to execute this specific operation.

**To Reproduce**
```python
import ttnn
import torch

device = ttnn.open_device(0)

tensor_a = torch.rand(1, 128, 2048)
tensor_b = torch.rand(7, 2048, 256)

tensor_c = torch.matmul(tensor_a, tensor_b)

print(tensor_c.shape)

a_tt = ttnn.from_torch(tensor_a, layout=ttnn.TILE_LAYOUT, device=device)
b_tt = ttnn.from_torch(tensor_b, layout=ttnn.TILE_LAYOUT, device=device)

c_tt = ttnn.matmul(a_tt, b_tt)

ttnn.close_device(device)
```

Error once the above code is executed:
```
Always | FATAL    | bmm (non-bcast matmul) expects input tensors of shapes BCMK*BCKN=BCMN or equivalent
Traceback (most recent call last):
  File "/localdev/sdjordjevic/src/tt-metal/simple_test.py", line 16, in <module>
    c_tt = ttnn.matmul(a_tt, b_tt)
  File "/localdev/sdjordjevic/src/tt-metal/ttnn/ttnn/decorators.py", line 326, in __call__
    return self.function(*function_args, **function_kwargs)
RuntimeError: TT_FATAL @ ../ttnn/cpp/ttnn/operations/matmul/device/matmul_op.cpp:975: a_shape[i] == b_shape[i]
info:
bmm (non-bcast matmul) expects input tensors of shapes BCMK*BCKN=BCMN or equivalent
backtrace:
 --- /localdev/sdjordjevic/src/tt-metal/ttnn/ttnn/_ttnn.so(+0x36f8a8) [0x7f086a4d88a8]
 --- ttnn::operations::matmul::Matmul::validate(std::__1::vector<tt::tt_metal::Tensor, std::__1::allocator<tt::tt_metal::Tensor>> const&, std::__1::vector<std::__1::optional<tt::tt_metal::Tensor const>, std::__1::allocator<std::__1::optional<tt::tt_metal::Tensor const>>> const&) const
```

**Expected behavior**
As stated in the public docs, in this particular case, the a input should be broadcasted from (1, 128, 2048) to (7, 128, 2048) and the matrix product executed.

**Screenshots**
N/A

**Please complete the following environment information:**
- OS: Ubuntu 20.04
- Version of software: Version of software: commit https://github.com/tenstorrent/tt-metal/commit/23b968f8cb5ae13b95d876d615599733903ce375

**Additional context**
N/A

**Comment by bbradelTT** [comment]
Only input_tensor_b can be broadcasted. That leads to some interesting corner cases (which the documentation processing has cut off, although that will need to be fixed separately), as well as not allowing input_tensor_b to be broadcasted.

I will need to update the documentation.

**Comment by bbradelTT** [comment]
Re: which the documentation processing has cut off, although that will need to be fixed separately
Turns out that https://docs.tenstorrent.com/ttnn/latest/ttnn/ttnn/matmul.html is really out of date and does not reflect existing documentation.

**Comment by bbradelTT** [comment]
Updated doc string with this scenario.

Doc string updated via PR https://github.com/tenstorrent/tt-metal/pull/13071

**Comment by bbradelTT** [comment]
@dgolubovicTT 
Do you mean that you want to multiply tensors with shapes like [1, M, K] x [b, K, N] and [1, 1, M, K] x [a, b, K, N]?

The complication is that matmul has multiple backends optimized for different scenarios. All the backends (or all except for the dram sharded one) would have to be updated and tested.

Instead of adding transposes, you might be able to do something like:
```
in0 = [1, M, K] tensor
in1 = [b, K, N] tensor
out = list
for i in range(b):
    in1_slice = slice(in1, start_indices=[i, 0, 0], end_indices=[i,K,N], increment[1,1,1])
   out[i] = matmul(in0, in1_view)
output = concat(out)
```

**Comment by bbradelTT** [comment]
This now works, if you modify the test to be the following:
```
import ttnn
import torch


def test_mm(device):
    # Reshape to rank-4 with a[1]=1 to enable the in0_reuse optimization that
    # allows batch dim mismatch on dim 1 (a=1 vs b=7).
    tensor_a = torch.rand(1, 1, 128, 2048)
    tensor_b = torch.rand(1, 7, 2048, 256)

    tensor_c = torch.matmul(tensor_a, tensor_b)

    print(tensor_c.shape)

    a_tt = ttnn.from_torch(tensor_a, layout=ttnn.TILE_LAYOUT, device=device)
    b_tt = ttnn.from_torch(tensor_b, layout=ttnn.TILE_LAYOUT, device=device)

    # Shapes in tiles (TILE_SIZE=32): M=128->4, K=2048->64, N=256->8.
    # in0_reuse requires MatmulMultiCoreReuseMultiCast1DProgramConfig with
    # fuse_batch=False, fused_activation=None, mcast_in0=False.
    program_config = ttnn.MatmulMultiCoreReuseMultiCast1DProgramConfig(
        compute_with_storage_grid_size=ttnn.CoreCoord(4, 1),
        in0_block_w=4,        # divides K_tiles=64
        out_subblock_h=1,     # divides per_core_M=1
        out_subblock_w=4,     # divides per_core_N=8; h*w<=4 (HW reg limit)
        per_core_M=1,         # M_tiles=4 split across 4 cores
        per_core_N=8,         # full N_tiles=8 per core
        fuse_batch=False,
        fused_activation=None,
        mcast_in0=False,
    )

    c_tt = ttnn.matmul(a_tt, b_tt, program_config=program_config)
```

However, this should be automatically dealt with. I will add this to the list of automatically choosing a program config issues.
