### ISSUE TITLE
Petr Model torch graph generation

### ISSUE THREAD

**Issue by punithsekar** [tenstorrent/tt-metal#14641]
In the PETR model, there are many sub_modules, I took PETRHead to generate a torch graph but I was not able to generate.

I have stored the PETR model, input values which is passed to it and then tried different tools to generate the PETRHead model graph,

## Method 1: 
	Using torchviz  Package, 

 Code:

```
import torch
img_metas=torch.load("/app/img_metas.pt")
mlvl_feats=torch.load("/app/mlvl_feats.pt")
torch_model=torch.load("/app/mmdetection3d/torch_model.pt")
torch_model = torch_model.pts_bbox_head 
from torchviz import make_dot
y = torch_model(mlvl_feats,img_metas)
dot = make_dot(y,params=dict(torch_model.named_parameters()))
dot.render("model_petrhead_model", format="png")  # Save as PNG
```

Error occurred, 

Traceback (most recent call last):
  File "/app/test_values.py", line 37, in <module>
    dot = make_dot(y)
  File "/opt/venv/lib/python3.8/site-packages/torchviz/dot.py", line 163, in make_dot
    add_base_tensor(var)
  File "/opt/venv/lib/python3.8/site-packages/torchviz/dot.py", line 146, in add_base_tensor
    if var in seen:
TypeError: unhashable type: 'dict'

## Method 2: 
	Using torchview Package

Code: 

```
from torchview import draw_graph
import torch
img_metas=torch.load("/app/img_metas.pt")
mlvl_feats=torch.load("/app/mlvl_feats.pt")
torch_model=torch.load("/app/mmdetection3d/torch_model.pt")
torch_model = torch_model.pts_bbox_head 
model_graph = draw_graph(
torch_model,
[mlvl_feats,img_metas],
dtypes=[torch.float32],
graph_name="model_petrHEAD",
)
model_graph.visual_graph.render(format="pdf")
```

Error:

Traceback (most recent call last):
  File "/app/test_values.py", line 20, in <module>
    model_graph = draw_graph(
  File "/opt/venv/lib/python3.8/site-packages/torchview/torchview.py", line 211, in draw_graph
    input_recorder_tensor, kwargs_record_tensor, input_nodes = process_input(
  File "/opt/venv/lib/python3.8/site-packages/torchview/torchview.py", line 283, in process_input
    x = set_device(input_data, device)
  File "/opt/venv/lib/python3.8/site-packages/torchview/torchview.py", line 377, in set_device
    return traverse_data(
  File "/opt/venv/lib/python3.8/site-packages/torchview/torchview.py", line 369, in traverse_data
    [traverse_data(d, action_fn, aggregate_fn) for d in data]
  File "/opt/venv/lib/python3.8/site-packages/torchview/torchview.py", line 369, in <listcomp>
    [traverse_data(d, action_fn, aggregate_fn) for d in data]
  File "/opt/venv/lib/python3.8/site-packages/torchview/torchview.py", line 369, in traverse_data
    [traverse_data(d, action_fn, aggregate_fn) for d in data]
  File "/opt/venv/lib/python3.8/site-packages/torchview/torchview.py", line 369, in <listcomp>
    [traverse_data(d, action_fn, aggregate_fn) for d in data]
  File "/opt/venv/lib/python3.8/site-packages/torchview/torchview.py", line 358, in traverse_data
    {
  File "/opt/venv/lib/python3.8/site-packages/torchview/torchview.py", line 359, in <dictcomp>
    k: traverse_data(v, action_fn, aggregate_fn)
  File "/opt/venv/lib/python3.8/site-packages/torchview/torchview.py", line 358, in traverse_data
    {
  File "/opt/venv/lib/python3.8/site-packages/torchview/torchview.py", line 359, in <dictcomp>
    k: traverse_data(v, action_fn, aggregate_fn)
  File "/opt/venv/lib/python3.8/site-packages/torchview/torchview.py", line 368, in traverse_data
    return aggregate(
TypeError: 'numpy.float32' object cannot be interpreted as an integer

## Method 3: 
   Using Hidden layer Package,

Code: 
```
import torch
img_metas=torch.load("/app/img_metas.pt")
mlvl_feats=torch.load("/app/mlvl_feats.pt")
torch_model=torch.load("/app/mmdetection3d/torch_model.pt")
torch_model = torch_model.pts_bbox_head 
import hiddenlayer as hl
hl.build_graph(torch_model, [mlvl_feats,img_metas]).save('Petr_head_graph.png')
```

Error:
 
Traceback (most recent call last):
  File "/app/test_values.py", line 32, in <module>
    hl.build_graph(torch_model, [mlvl_feats,img_metas]).save('hidden_layer_graph.png')
  File "/opt/venv/lib/python3.8/site-packages/hiddenlayer/graph.py", line 143, in build_graph
    import_graph(g, model, args)
  File "/opt/venv/lib/python3.8/site-packages/hiddenlayer/pytorch_builder.py", line 70, in import_graph
    trace, out = torch.jit._get_trace_graph(model, args)
  File "/opt/venv/lib/python3.8/site-packages/torch/jit/_trace.py", line 1160, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/torch/jit/_trace.py", line 95, in forward
    in_vars, in_desc = _flatten(args)
RuntimeError: Only tuples, lists and Variables are supported as JIT inputs/outputs. Dictionaries and strings are also accepted, but their usage is not recommended. Here, received an input of unsupported type: type

Inputs to PETRHead forward,
mlvl_feats
img_metas

mlvl_feats is type of tuple[Tensor].
img_metas is type List

Example value of img_metas for reference,

```
Img_mets = [{'box_type_3d': <class 'mmdet3d.structures.bbox_3d.lidar_box3d.LiDARInstance3DBoxes'>, 'box_mode_3d': <Box3DMode.LIDAR: 0>, 'img_shape': [(900, 1600), (900, 1600), (900, 1600), (900, 1600), (900, 1600), (900, 1600)], 'scale_factor': 1.0, 'num_ref_frames': -1, 'num_pts_feats': 5, 'lidar_path': 'data/nuscenes/samples/LIDAR_TOP/n008-2018-08-01-15-16-36-0400__LIDAR_TOP__1533151603547590.pcd.bin', 'img_norm_cfg': {'mean': array([0., 0., 0.], dtype=float32), 'std': array([1., 1., 1.], dtype=float32), 'to_rgb': False}, 'img_path': ['data/nuscenes/samples/CAM_FRONT/n008-2018-08-01-15-16-36-0400__CAM_FRONT__1533151603512404.jpg', 'data/nuscenes/samples/CAM_FRONT_RIGHT/n008-2018-08-01-15-16-36-0400__CAM_FRONT_RIGHT__1533151603520482.jpg', 'data/nuscenes/samples/CAM_FRONT_LEFT/n008-2018-08-01-15-16-36-0400__CAM_FRONT_LEFT__1533151603504799.jpg', 'data/nuscenes/samples/CAM_BACK/n008-2018-08-01-15-16-36-0400__CAM_BACK__1533151603537558.jpg', 'data/nuscenes/samples/CAM_BACK_LEFT/n008-2018-08-01-15-16-36-0400__CAM_BACK_LEFT__1533151603547405.jpg', 'data/nuscenes/samples/CAM_BACK_RIGHT/n008-2018-08-01-15-16-36-0400__CAM_BACK_RIGHT__1533151603528113.jpg'], 'cam2img': [array([[626.40655106,   0.        , 413.29405739,   0.        ],
       [  0.        , 626.40655106, 104.99233131,   0.        ],
       [  0.        ,   0.        ,   1.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   1.        ]]), array([[628.37425582,   0.        , 408.89437855,   0.        ],
       [  0.        , 628.37425582,  95.977089  ,   0.        ],
       [  0.        ,   0.        ,   1.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   1.        ]]), array([[628.93126711,   0.        , 413.62053155,   0.        ],
       [  0.        , 628.93126711,  95.4577491 ,   0.        ],
       [  0.        ,   0.        ,   1.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   1.        ]]), array([[398.44553173,   0.        , 428.88871634,   0.        ],
       [  0.        , 398.44553173, 108.44244942,   0.        ],
       [  0.        ,   0.        ,   1.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   1.        ]]), array([[627.49302829,   0.        , 414.78846668,   0.        ],
       [  0.        , 627.49302829, 103.58402809,   0.        ],
       [  0.        ,   0.        ,   1.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   1.        ]]), array([[624.98146404,   0.        , 412.68840227,   0.        ],
       [  0.        , 624.98146404, 101.27408193,   0.        ],
       [  0.        ,   0.        ,   1.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   1.        ]])], 'sample_idx': 0, 'lidar2cam': array([[[ 0.99988014,  0.01223258, -0.00949188, -0.00230111],
        [-0.0101382 ,  0.05390463, -0.99849463, -0.3550958 ],
        [-0.0117025 ,  0.99847114,  0.05402219, -0.42520365],
        [ 0.        ,  0.        ,  0.        ,  1.        ]],

       [[ 0.53727371, -0.84173948, -0.05302503,  0.02984876],
        [-0.00136775,  0.06200032, -0.99807519, -0.33156687],
        [ 0.84340686,  0.53631204,  0.03215985, -0.61037183],
        [ 0.        ,  0.        ,  0.        ,  1.        ]],

       [[ 0.56725818,  0.8228128 ,  0.034602  ,  0.10790747],
        [-0.01433343,  0.05187402, -0.99855077, -0.35026494],
        [-0.82341528,  0.56594008,  0.04121969, -0.52967709],
        [ 0.        ,  0.        ,  0.        ,  1.        ]],

       [[-0.99992836,  0.00799071,  0.00891444,  0.00137395],
        [-0.00859485,  0.03917429, -0.99919546, -0.28103328],
        [-0.0083335 , -0.99920046, -0.0391028 , -1.0164535 ],
        [ 0.        ,  0.        ,  0.        ,  1.        ]],

       [[-0.31910315,  0.94686079,  0.04034692, -0.21237409],
        [-0.01589121,  0.03722081, -0.99918073, -0.28666893],
        [-0.94758677, -0.31948286,  0.00316949, -0.4325273 ],
        [ 0.        ,  0.        ,  0.        ,  1.        ]],

       [[-0.38201341, -0.92305064, -0.04520244,  0.08872823],
        [ 0.01385406,  0.04318667, -0.99897099, -0.29866916],
        [ 0.92405295, -0.38224655, -0.00370989, -0.46464515],
        [ 0.        ,  0.        ,  0.        ,  1.        ]]]), 'num_views': 5, 'batch_input_shape': (320, 800), 'ego2global': [[0.8766746520996094, 0.48091214895248413, 0.012845641002058983, 600.1202392578125], [-0.48078814148902893, 0.8767595291137695, -0.011639153584837914, 1647.49072265625], [-0.01685994863510132, 0.004027719609439373, 0.9998497366905212, 0.0], [0.0, 0.0, 0.0, 1.0]], 'ori_cam2img': [[[1252.8131021185304, 0.0, 826.588114781398], [0.0, 1252.8131021185304, 469.9846626224581], [0.0, 0.0, 1.0]], [[1256.7485116440405, 0.0, 817.7887570959712], [0.0, 1256.7485116440403, 451.9541780095127], [0.0, 0.0, 1.0]], [[1257.8625342125129, 0.0, 827.2410631095686], [0.0, 1257.8625342125129, 450.915498205774], [0.0, 0.0, 1.0]], [[796.8910634503094, 0.0, 857.7774326863696], [0.0, 796.8910634503094, 476.8848988407415], [0.0, 0.0, 1.0]], [[1254.9860565800168, 0.0, 829.5769333630991], [0.0, 1254.9860565800168, 467.1680561863987], [0.0, 0.0, 1.0]], [[1249.9629280788233, 0.0, 825.3768045375984], [0.0, 1249.9629280788233, 462.54816385708756], [0.0, 0.0, 1.0]]], 'ori_shape': (900, 1600), 'pad_shape': (320, 800), 'lidar2img': [tensor([[ 6.2149e+02,  4.2032e+02,  1.6381e+01, -1.7718e+02],
      [-7.5793e+00,  1.3860e+02, -6.1979e+02, -2.6708e+02],
      [-1.1703e-02,  9.9847e-01,  5.4022e-02, -4.2520e-01],
      [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00]],
     dtype=torch.float64), tensor([[ 6.8247e+02, -3.0963e+02, -2.0170e+01, -2.3082e+02],
      [ 8.0088e+01,  9.0433e+01, -6.2408e+02, -2.6693e+02],
      [ 8.4341e-01,  5.3631e-01,  3.2160e-02, -6.1037e-01],
      [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00]],
     dtype=torch.float64), tensor([[ 1.6185e+01,  7.5158e+02,  3.8812e+01, -1.5122e+02],
      [-8.7616e+01,  8.6649e+01, -6.2409e+02, -2.7085e+02],
      [-8.2342e-01,  5.6594e-01,  4.1220e-02, -5.2968e-01],
      [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00]],
     dtype=torch.float64), tensor([[-4.0199e+02, -4.2536e+02, -1.3219e+01, -4.3540e+02],
      [-4.3283e+00, -9.2747e+01, -4.0237e+02, -2.2220e+02],
      [-8.3335e-03, -9.9920e-01, -3.9103e-02, -1.0165e+00],
      [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00]],
     dtype=torch.float64), tensor([[-5.9328e+02,  4.6163e+02,  2.6632e+01, -3.1267e+02],
      [-1.0813e+02, -9.7375e+00, -6.2665e+02, -2.2469e+02],
      [-9.4759e-01, -3.1948e-01,  3.1695e-03, -4.3253e-01],
      [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00]],
     dtype=torch.float64), tensor([[ 1.4259e+02, -7.3464e+02, -2.9782e+01, -1.3630e+02],
      [ 1.0224e+02, -1.1721e+01, -6.2471e+02, -2.3372e+02],
      [ 9.2405e-01, -3.8225e-01, -3.7099e-03, -4.6465e-01],
      [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00]],
     dtype=torch.float64)], 'input_shape': torch.Size([320, 800])}]

```

**Comment by punithsekar** [comment]
fyi @saichandax

**Comment by punithsekar** [comment]
This is not a issue that need fix, This issue is only to have track of the graph progress.

**Comment by saichandax** [comment]
Closing the issue. No longer relevant. Re-open if necessary.
