### ISSUE TITLE
[Bug Report] Host side memory leak in device memory allocator

### ISSUE THREAD

**Issue by marty1885** [tenstorrent/tt-metal#15407]
**Describe the bug**
ASan reports the following error when I run Metalium programs, upon program exit.

```
=================================================================
==64845==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 32832 byte(s) in 228 object(s) allocated from:
    #0 0x792308afe4f2 in operator new(unsigned long) /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_new_delete.cpp:95
    #1 0x792306d5562b in std::__new_allocator<boost::detail::sp_counted_impl_pda<tt::tt_metal::allocator::FreeList::Block*, boost::detail::lsp_ms_deleter<tt::tt_metal::allocator::FreeList::Block, std::allocator<tt::tt_metal::allocator::FreeList::Block> >, std::allocator<tt::tt_metal::allocator::FreeList::Block> > >::allocate(unsigned long, void const*) /usr/include/c++/14.2.1/bits/new_allocator.h:151
    #2 0x792306d5562b in std::allocator<boost::detail::sp_counted_impl_pda<tt::tt_metal::allocator::FreeList::Block*, boost::detail::lsp_ms_deleter<tt::tt_metal::allocator::FreeList::Block, std::allocator<tt::tt_metal::allocator::FreeList::Block> >, std::allocator<tt::tt_metal::allocator::FreeList::Block> > >::allocate(unsigned long) /usr/include/c++/14.2.1/bits/allocator.h:196
    #3 0x792306d5562b in boost::detail::shared_count::shared_count<tt::tt_metal::allocator::FreeList::Block*, boost::detail::lsp_ms_deleter<tt::tt_metal::allocator::FreeList::Block, std::allocator<tt::tt_metal::allocator::FreeList::Block> >, std::allocator<tt::tt_metal::allocator::FreeList::Block> >(tt::tt_metal::allocator::FreeList::Block*, boost::detail::sp_inplace_tag<boost::detail::lsp_ms_deleter<tt::tt_metal::allocator::FreeList::Block, std::allocator<tt::tt_metal::allocator::FreeList::Block> > >, std::allocator<tt::tt_metal::allocator::FreeList::Block>) /home/marty/Documents/tt/tt-metal/.cpmcache/boost_smart_ptr/46e365a5a6d5492f115758349a9eefaa61cd0a2e/include/boost/smart_ptr/detail/shared_count.hpp:322
    #4 0x792306d5562b in boost::shared_ptr<tt::tt_metal::allocator::FreeList::Block>::shared_ptr<tt::tt_metal::allocator::FreeList::Block, boost::detail::sp_inplace_tag<boost::detail::lsp_ms_deleter<tt::tt_metal::allocator::FreeList::Block, std::allocator<tt::tt_metal::allocator::FreeList::Block> > >, std::allocator<tt::tt_metal::allocator::FreeList::Block> >(tt::tt_metal::allocator::FreeList::Block*, boost::detail::sp_inplace_tag<boost::detail::lsp_ms_deleter<tt::tt_metal::allocator::FreeList::Block, std::allocator<tt::tt_metal::allocator::FreeList::Block> > >, std::allocator<tt::tt_metal::allocator::FreeList::Block>) /home/marty/Documents/tt/tt-metal/.cpmcache/boost_smart_ptr/46e365a5a6d5492f115758349a9eefaa61cd0a2e/include/boost/smart_ptr/shared_ptr.hpp:421
    #5 0x792306d5562b in boost::detail::lsp_if_not_array<tt::tt_metal::allocator::FreeList::Block>::type boost::allocate_local_shared<tt::tt_metal::allocator::FreeList::Block, std::allocator<tt::tt_metal::allocator::FreeList::Block>, unsigned long, unsigned long&>(std::allocator<tt::tt_metal::allocator::FreeList::Block> const&, unsigned long&&, unsigned long&) /home/marty/Documents/tt/tt-metal/.cpmcache/boost_smart_ptr/46e365a5a6d5492f115758349a9eefaa61cd0a2e/include/boost/smart_ptr/make_local_shared_object.hpp:131
    #6 0x792306d5562b in boost::detail::lsp_if_not_array<tt::tt_metal::allocator::FreeList::Block>::type boost::make_local_shared<tt::tt_metal::allocator::FreeList::Block, unsigned long, unsigned long&>(unsigned long&&, unsigned long&) /home/marty/Documents/tt/tt-metal/.cpmcache/boost_smart_ptr/46e365a5a6d5492f115758349a9eefaa61cd0a2e/include/boost/smart_ptr/make_local_shared_object.hpp:192
    #7 0x792306d5562b in tt::tt_metal::allocator::FreeList::allocate_slice_of_free_block(boost::local_shared_ptr<tt::tt_metal::allocator::FreeList::Block>, unsigned long, unsigned long) /home/marty/Documents/tt/tt-metal/tt_metal/impl/allocator/algorithms/free_list.cpp:166
    #8 0x792306d56055 in tt::tt_metal::allocator::FreeList::allocate(unsigned long, bool, unsigned long) /home/marty/Documents/tt/tt-metal/tt_metal/impl/allocator/algorithms/free_list.cpp:238
    #9 0x792306d604c8 in tt::tt_metal::allocator::BankManager::allocate_buffer(unsigned long, unsigned long, bool, CoreRangeSet const&, std::optional<unsigned int>) /home/marty/Documents/tt/tt-metal/tt_metal/impl/allocator/allocator.cpp:136
```

~~I have looked into the codebase and I think I understand what is causing the trouble. In both `update_left_aligned_allocated_block_connections` and `update_right_aligned_allocated_block_connections` , assignment of shared pointers forms a circular reference. Take one of the functions for example.~~

Turns out the problem is related, but not quite right. The circular dependency is true. However `deallocate()` correctly demangles the reference. On allocator destruction, no code is present to demangle the list. Leading to RAII unable to clean up allocations made.

```c++
void FreeList::update_left_aligned_allocated_block_connections(boost::local_shared_ptr<Block> free_block, boost::local_shared_ptr<Block> allocated_block) {
    allocated_block->prev_block = free_block->prev_block;
    allocated_block->next_block = free_block; // allocated_block holds pointer to free_block
    if (free_block->prev_block != nullptr) {
        free_block->prev_block->next_block = allocated_block;
    }
    if (free_block == this->block_head_) {
        this->block_head_ = allocated_block;
    }
    // next_free and prev_free connections of free_block are still valid
    free_block->prev_block = allocated_block; // free_block holds pointer to allocated_block
    free_block->address = allocated_block->address + allocated_block->size;
    free_block->size -= allocated_block->size;
}

```

I do not have enough context in this area of code to create a fix. I assume a proper fix is either know the block all always only have one owner and use a pair of `unique_ptr` and raw pointer. or use a weak reference to avoid the circular dependency. Though that leads to the control block almost never being deallocated.

I like the 1st solution better as it should eliminate  the shared pointer copying in the allocator, which is quite expensive. Personally I'd architecture to what Rust would do - have a container that actually holds the objects to guarantee lifetime, then use raw pointers in the blocks.

**To Reproduce**
1. Build metalium with ASan
2. Run any TTNN example
3. See memory leak

**Expected behavior**
No leak

**Screenshots**

**Please complete the following environment information:**
- Commit: `cbe17c327193babce1a93c00396e835bb04fdc99`

**Additional context**

**Comment by ayerofieiev-tt** [comment]
Thank you for the report and the initial analysis!

**Comment by marty1885** [comment]
I ended up cooking my own solution as the problem interferes with some debugging. Please give it a look and feel free to close it if you think there's a batter/easier way.

**Comment by pgkeller** [comment]
@abhullar-tt @patrickroberts fyi

**Comment by abhullar-tt** [comment]
Thanks Marty for catching this! I took your PR https://github.com/tenstorrent/tt-metal/pull/15410 and I am running it against our CI. This can be checked in for the fix to this issue but we can make some more improvements to the allocator implementation

**Comment by marty1885** [comment]
Closing as the solution has been merged.
