### ISSUE TITLE
[Bug Report] TTNN Fill operation fails for a shape [1]

### ISSUE THREAD

**Issue by sdjordjevicTT** [tenstorrent/tt-metal#16312]
**Describe the bug**
After the following PR and commit(212be31):
https://github.com/tenstorrent/tt-metal/pull/16072

We identified a failing test and regression in the MLIR compiler repo while uplifting the new metal code into our repo. The issue is with the full op where it fails with the following error message:
`Host data with total size 128B does not match expected size 4096B of device buffer!`

**To Reproduce**
The following TTNN Python test should reproduce the failure:
```python
import ttnn

device = ttnn.open_device(device_id=0)

fill_tensor = ttnn.full(shape=[1], fill_value=0, device=device, dtype=ttnn.uint32, layout=ttnn.TILE_LAYOUT, memory_config=ttnn.DRAM_MEMORY_CONFIG)

print(fill_tensor.shape)
print(fill_tensor.layout)

ttnn.close_device(device)
```

The failure stack trace:
```
Always | FATAL    | Host data with total size 128B does not match expected size 4096B of device buffer!
Traceback (most recent call last):
  File "/localdev/sdjordjevic/src/tt-metal/python_test.py", line 6, in <module>
    fill_tensor = ttnn.full(shape=[1], fill_value=0, device=device, dtype=ttnn.uint32, layout=ttnn.TILE_LAYOUT, memory_config=ttnn.DRAM_MEMORY_CONFIG)
  File "/localdev/sdjordjevic/src/tt-metal/ttnn/ttnn/decorators.py", line 329, in __call__
    return self.function(*function_args, **function_kwargs)
RuntimeError: TT_FATAL @ /localdev/sdjordjevic/src/tt-metal/ttnn/cpp/ttnn/tensor/tensor_impl.cpp:716: input_size_bytes == expected_packed_buffer_size_bytes
info:
Host data with total size 128B does not match expected size 4096B of device buffer!
backtrace:
 --- /localdev/sdjordjevic/src/tt-metal/ttnn/ttnn/_ttnn.so(+0x8a4609) [0x7fd911003609]
 --- /localdev/sdjordjevic/src/tt-metal/ttnn/ttnn/_ttnn.so(+0x1e757a1) [0x7fd9125d47a1]
 --- /localdev/sdjordjevic/src/tt-metal/ttnn/ttnn/_ttnn.so(+0x1e755ec) [0x7fd9125d45ec]
 --- tt::tt_metal::Tensor tt::tt_metal::tensor_impl::to_device<unsigned int>(tt::tt_metal::Tensor const&, tt::tt_metal::v0::Device*, tt::tt_metal::MemoryConfig const&, unsigned char, tt::stl::Span<tt::tt_metal::SubDeviceId const, 18446744073709551615ul>)
 --- auto tt::tt_metal::tensor_impl::dispatch<auto tt::tt_metal::tensor_impl::to_device_wrapper<tt::tt_metal::Tensor&, tt::tt_metal::v0::Device* const&, tt::tt_metal::MemoryConfig const&, unsigned char&, std::__1::vector<tt::tt_metal::SubDeviceId, std::__1::allocator<tt::tt_metal::SubDeviceId>> const&>(tt::tt_metal::Tensor&, tt::tt_metal::v0::Device* const&, tt::tt_metal::MemoryConfig const&, unsigned char&, std::__1::vector<tt::tt_metal::SubDeviceId, std::__1::allocator<tt::tt_metal::SubDeviceId>> const&)::'lambda'<typename $T>(auto&&...), tt::tt_metal::Tensor&, tt::tt_metal::v0::Device* const&, tt::tt_metal::MemoryConfig const&, unsigned char&, std::__1::vector<tt::tt_metal::SubDeviceId, std::__1::allocator<tt::tt_metal::SubDeviceId>> const&>(tt::tt_metal::DataType, auto tt::tt_metal::tensor_impl::to_device_wrapper<tt::tt_metal::Tensor&, tt::tt_metal::v0::Device* const&, tt::tt_metal::MemoryConfig const&, unsigned char&, std::__1::vector<tt::tt_metal::SubDeviceId, std::__1::allocator<tt::tt_metal::SubDeviceId>> const&>(tt::tt_metal::Tensor&, tt::tt_metal::v0::Device* const&, tt::tt_metal::MemoryConfig const&, unsigned char&, std::__1::vector<tt::tt_metal::SubDeviceId, std::__1::allocator<tt::tt_metal::SubDeviceId>> const&)::'lambda'<typename $T>(auto&&...)&&, auto&&...)
 --- /localdev/sdjordjevic/src/tt-metal/ttnn/ttnn/_ttnn.so(+0x1d72247) [0x7fd9124d1247]
 --- tt::tt_metal::tensor_ops::tensor_to(tt::tt_metal::Tensor const&, std::__1::vector<tt::tt_metal::v0::Device*, std::__1::allocator<tt::tt_metal::v0::Device*>> const&, tt::tt_metal::MemoryConfig const&, unsigned char, std::__1::vector<tt::tt_metal::SubDeviceId, std::__1::allocator<tt::tt_metal::SubDeviceId>> const&)
 --- tt::tt_metal::Tensor::to(std::__1::vector<tt::tt_metal::v0::Device*, std::__1::allocator<tt::tt_metal::v0::Device*>> const&, tt::tt_metal::MemoryConfig const&, unsigned char, std::__1::vector<tt::tt_metal::SubDeviceId, std::__1::allocator<tt::tt_metal::SubDeviceId>> const&) const
 --- /localdev/sdjordjevic/src/tt-metal/ttnn/ttnn/_ttnn.so(+0x98446e) [0x7fd9110e346e]
 --- /localdev/sdjordjevic/src/tt-metal/ttnn/ttnn/_ttnn.so(+0xa8788b) [0x7fd9111e688b]
 --- /localdev/sdjordjevic/src/tt-metal/ttnn/ttnn/_ttnn.so(+0xa87400) [0x7fd9111e6400]
 --- /localdev/sdjordjevic/src/tt-metal/ttnn/ttnn/_ttnn.so(+0xa872aa) [0x7fd9111e62aa]
 --- /localdev/sdjordjevic/src/tt-metal/ttnn/ttnn/_ttnn.so(+0xa87029) [0x7fd9111e6029]
 --- /localdev/sdjordjevic/src/tt-metal/ttnn/ttnn/_ttnn.so(+0xa86e0e) [0x7fd9111e5e0e]
 --- /localdev/sdjordjevic/src/tt-metal/ttnn/ttnn/_ttnn.so(+0xa86a52) [0x7fd9111e5a52]
 --- /localdev/sdjordjevic/src/tt-metal/ttnn/ttnn/_ttnn.so(+0xa8699e) [0x7fd9111e599e]
 --- /localdev/sdjordjevic/src/tt-metal/ttnn/ttnn/_ttnn.so(+0x44f789) [0x7fd910bae789]
 --- /localdev/sdjordjevic/src/tt-metal/python_env/bin/python(+0x18b282) [0x5600beb8a282]
 --- /localdev/sdjordjevic/src/tt-metal/python_env/bin/python(_PyObject_MakeTpCall+0x25b) [0x5600beb80b4b]
 --- /localdev/sdjordjevic/src/tt-metal/python_env/bin/python(+0x198ebb) [0x5600beb97ebb]
 --- /localdev/sdjordjevic/src/tt-metal/python_env/bin/python(_PyObject_Call+0x118) [0x5600beb98a28]
 --- /localdev/sdjordjevic/src/tt-metal/python_env/bin/python(+0x29e07f) [0x5600bec9d07f]
 --- /localdev/sdjordjevic/src/tt-metal/python_env/bin/python(PyObject_Call+0xbb) [0x5600beb9881b]
 --- /localdev/sdjordjevic/src/tt-metal/python_env/bin/python(_PyEval_EvalFrameDefault+0x2c89) [0x5600beb76f59]
 --- /localdev/sdjordjevic/src/tt-metal/python_env/bin/python(_PyFunction_Vectorcall+0x7c) [0x5600beb8aaec]
 --- /localdev/sdjordjevic/src/tt-metal/python_env/bin/python(_PyObject_FastCallDictTstate+0x16d) [0x5600beb7fdbd]
 --- /localdev/sdjordjevic/src/tt-metal/python_env/bin/python(_PyObject_Call_Prepend+0x5c) [0x5600beb94d4c]
 --- /localdev/sdjordjevic/src/tt-metal/python_env/bin/python(+0x29e054) [0x5600bec9d054]
 --- /localdev/sdjordjevic/src/tt-metal/python_env/bin/python(_PyObject_MakeTpCall+0x25b) [0x5600beb80b4b]
 --- /localdev/sdjordjevic/src/tt-metal/python_env/bin/python(_PyEval_EvalFrameDefault+0x671a) [0x5600beb7a9ea]
 --- /localdev/sdjordjevic/src/tt-metal/python_env/bin/python(+0x25ae56) [0x5600bec59e56]
 --- /localdev/sdjordjevic/src/tt-metal/python_env/bin/python(PyEval_EvalCode+0x86) [0x5600bec59d26]
 --- /localdev/sdjordjevic/src/tt-metal/python_env/bin/python(+0x281ae8) [0x5600bec80ae8]
 --- /localdev/sdjordjevic/src/tt-metal/python_env/bin/python(+0x27c2ef) [0x5600bec7b2ef]
 --- /localdev/sdjordjevic/src/tt-metal/python_env/bin/python(+0x281885) [0x5600bec80885]
 --- /localdev/sdjordjevic/src/tt-metal/python_env/bin/python(_PyRun_SimpleFileObject+0x1a8) [0x5600bec7fe68]
 --- /localdev/sdjordjevic/src/tt-metal/python_env/bin/python(_PyRun_AnyFileObject+0x47) [0x5600bec7fb47]
 --- /localdev/sdjordjevic/src/tt-metal/python_env/bin/python(Py_RunMain+0x2be) [0x5600bec7402e]
 --- /localdev/sdjordjevic/src/tt-metal/python_env/bin/python(Py_BytesMain+0x2d) [0x5600bec4dd6d]
 --- /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7fd914e1cd90]
 --- /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7fd914e1ce40]
 --- /localdev/sdjordjevic/src/tt-metal/python_env/bin/python(_start+0x25) [0x5600bec4dc65]
```

**Expected behavior**
The expected behavior is that this test passes.

**Screenshots**
N/A

**Please complete the following environment information:**
- OS: Ubuntu 22
- Version of software: Failure detected after committing 212be31

**Additional context**

**Comment by sdjordjevicTT** [comment]
Hi, @TT-BrianLiu this issue currently blocks our efforts to uplift the metal code version in our MLIR compiler repo. Can you please help us unblock?

**Comment by cmaryanTT** [comment]
@ntarafdar - FYI

**Comment by sdjordjevicTT** [comment]
@TT-BrianLiu yes, that is exactly what I was thinking. I hope someone will look at this, as this blocks our tests on the MLIR compiler side.

**Comment by TT-BrianLiu** [comment]
This should fix it. Waiting for pipelines to pass. https://github.com/tenstorrent/tt-metal/pull/16562
