### ISSUE TITLE
Investigate non-deterministic in ttnn integration test in fast dispatch frequent pipeline

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#4708]
https://github.com/tenstorrent-metal/tt-metal/actions/runs/7503814384

ps aux | grep metal on runner:

```
ubuntu@3606d97b-b957-4261-be13-70977307a1cc:~$ ps aux | grep metal
root       17893  102 24.4 19469508 12071772 ?   Rl   15:09 155:03 /home/ubuntu/actions-runner/_work/tt-metal/tt-metal/build/python_env/bin/python /home/ubuntu/actions-runner/_work/tt-metal/tt-metal/build/python_env/bin/pytest tests/ttnn/integration_tests
ubuntu     27915  0.0  0.0   8160  2376 pts/0    S+   17:40   0:00 grep --color=auto metal
```

with gdb stack:

```
#0  0x00007f20c984e588 in std::pair<int const, void*>& std::forward<std::pair<int const, void*>&>(std::remove_reference<std::pair<int const, void*>&>::type&) () from /home/ubuntu/actions-runner/_work/tt-metal/tt-metal/build/lib/libtt_metal.so
#1  0x00007f20c984e549 in std::__detail::_Select1st::operator()<std::pair<int const, void*>&> () from /home/ubuntu/actions-runner/_work/tt-metal/tt-metal/build/lib/libtt_metal.so
#2  0x00007f20c984e4cc in std::__detail::_Equal_helper<int, std::pair<int const, void*>, std::__detail::_Select1st, std::equal_to<int>, unsigned long, false>::_S_equals(std::equal_to<int> const&, std::__detail::_Select1st const&, int const&, unsigned long, std::__detail::_Hash_node<std::pair<int const, void*>, false>*) () from /home/ubuntu/actions-runner/_work/tt-metal/tt-metal/build/lib/libtt_metal.so
#3  0x00007f20c984e440 in std::__detail::_Hashtable_base<int, std::pair<int const, void*>, std::__detail::_Select1st, std::equal_to<int>, std::hash<int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Hashtable_traits<false, false, true> >::_M_equals(int const&, unsigned long, std::__detail::_Hash_node<std::pair<int const, void*>, false>*) const () from /home/ubuntu/actions-runner/_work/tt-metal/tt-metal/build/lib/libtt_metal.so
#4  0x00007f20c984e36a in std::_Hashtable<int, std::pair<int const, void*>, std::allocator<std::pair<int const, void*> >, std::__detail::_Select1st, std::equal_to<int>, std::hash<int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_find_before_node(unsigned long, int const&, unsigned long) const () from /home/ubuntu/actions-runner/_work/tt-metal/tt-metal/build/lib/libtt_metal.so
#5  0x00007f20c984df2d in std::_Hashtable<int, std::pair<int const, void*>, std::allocator<std::pair<int const, void*> >, std::__detail::_Select1st, std::equal_to<int>, std::hash<int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_find_node(unsigned long, int const&, unsigned long) const () from /home/ubuntu/actions-runner/_work/tt-metal/tt-metal/build/lib/libtt_metal.so
#6  0x00007f20c985113e in std::__detail::_Map_base<int, std::pair<int const, void*>, std::allocator<std::pair<int const, void*> >, std::__detail::_Select1st, std::equal_to<int>, std::hash<int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>, true>::at(int const&) () from /home/ubuntu/actions-runner/_work/tt-metal/tt-metal/build/lib/libtt_metal.so
#7  0x00007f20c9804738 in std::unordered_map<int, void*, std::hash<int>, std::equal_to<int>, std::allocator<std::pair<int const, void*> > >::at(int const&) () from /home/ubuntu/actions-runner/_work/tt-metal/tt-metal/build/lib/libtt_metal.so
#8  0x00007f20c97e7166 in tt_SiliconDevice::read_dma_buffer(void*, unsigned int, unsigned short, unsigned int, int) () from /home/ubuntu/actions-runner/_work/tt-metal/tt-metal/build/lib/libtt_metal.so
#9  0x00007f20c97f8af7 in tt_SiliconDevice::read_from_sysmem(void*, unsigned long, unsigned short, unsigned int, int) () from /home/ubuntu/actions-runner/_work/tt-metal/tt-metal/build/lib/libtt_metal.so
#10 0x00007f20c99635c5 in tt::Cluster::read_sysmem (this=0x7f20c9a72a40 <tt::Cluster::instance()::inst>, vec=vec@entry=0x7fff50adec7c, size_in_bytes=size_in_bytes@entry=4, addr=addr@entry=64, src_device_id=<optimized out>, src_device_id@entry=0, 
    channel=channel@entry=0) at tt_metal/llrt/tt_cluster.cpp:498
#11 0x00007f20c994a73e in tt::tt_metal::CommandQueue::finish (this=<optimized out>) at tt_metal/impl/dispatch/command_queue.cpp:1024
#12 0x00007f20c994ac91 in tt::tt_metal::CommandQueue::enqueue_read_buffer (this=<optimized out>, buffer=..., dst=<optimized out>, blocking=<optimized out>) at tt_metal/impl/dispatch/command_queue.cpp:863
#13 0x00007f20c994b9ce in tt::tt_metal::EnqueueReadBuffer (cq=..., buffer=..., dst=dst@entry=0x6d35690, blocking=blocking@entry=true) at tt_metal/impl/dispatch/command_queue.cpp:1063
#14 0x00007f20c9ee0d17 in tt::tt_metal::tensor_impl::read_data_from_device<bfloat16> (tensor=..., size_in_bytes=<optimized out>) at /usr/include/c++/9/bits/unique_ptr.h:360
#15 0x00007f20c9ff204b in tt::tt_metal::tensor_impl::to_host<bfloat16> (tensor=...) at ./tt_metal/impl/buffers/buffer.hpp:131
#16 0x00007f20c9fd1b76 in std::_Function_handler<tt::tt_metal::Tensor (tt::tt_metal::Tensor const&), tt::tt_metal::Tensor (*)(tt::tt_metal::Tensor const&)>::_M_invoke(std::_Any_data const&, tt::tt_metal::Tensor const&) (__functor=..., __args#0=...)
    at /usr/include/c++/9/bits/std_function.h:88
#17 0x00007f20c9fcff04 in std::function<tt::tt_metal::Tensor (tt::tt_metal::Tensor const&)>::operator()(tt::tt_metal::Tensor const&) const (__args#0=..., this=<optimized out>) at /usr/include/c++/9/bits/std_function.h:683
#18 tt::tt_metal::tensor_impl::to_host_wrapper (tensor=...) at tt_eager/tensor/tensor_impl_wrapper.cpp:46
#19 0x00007f20c9fc4ceb in tt::tt_metal::Tensor::cpu (this=0x546fa4d0) at tt_eager/tensor/tensor.cpp:123
```

looks like it's stuck on device when I check proc stack:

```
ubuntu@3606d97b-b957-4261-be13-70977307a1cc:~$ sudo cat /proc/17893/stack
[<0>] exit_to_usermode_loop+0x8f/0x160
[<0>] prepare_exit_to_usermode+0x6f/0xa0
[<0>] ret_from_intr+0x25/0x25
```

**Comment by tt-rkim** [comment]
cc: @arakhmati @DrJessop @jliangTT 

Akhmed and I think this is exposing some issue, unsure where exactly. Looks like it's stuck trying to read a tensor back to CPU?

We need to discuss priority and who to assign to investigate. One step to check is to see if watcher can detect anything bad.

**Comment by davorchap** [comment]
@tt-rkim and @arakhmati  this still a problem?
