### ISSUE TITLE
[N300] TTNN Unit Test Failures: Op PCC failures

### ISSUE THREAD

**Issue by cfjchu** [tenstorrent/tt-metal#6991]
Eltwise Unary failures:

```
FAILED tests/ttnn/unit_tests/operations/test_unary.py::test_gelu[w=128-h=64] - AssertionError: 0.9996086108852655
FAILED tests/ttnn/unit_tests/operations/test_unary.py::test_asinh[w=128-h=64] - AssertionError: 0.999800979188091
FAILED tests/ttnn/unit_tests/operations/test_unary.py::test_acosh[w=128-h=64] - AssertionError: 0.0
FAILED tests/ttnn/unit_tests/operations/test_unary.py::test_logit[w=128-h=64-scalar=2] - AssertionError: 0.0
```

Will be disabling this test while I enable N300 unit test suite. fyi @jliangTT @xanderchin

**Comment by umadevimcw** [comment]
@cfjchu Except acosh and logit all other tests are passing in the recent main. For testing, I have removed the skip statement and tested it. Attached the images below for your reference

<img width="1142" alt="Screenshot 2024-04-09 at 6 27 41 PM" src="https://github.com/tenstorrent-metal/tt-metal/assets/29221091/e9755ec3-3df8-4c55-a2ce-d72c63fe7d66">

<img width="1140" alt="Screenshot 2024-04-09 at 6 23 56 PM" src="https://github.com/tenstorrent-metal/tt-metal/assets/29221091/288c5ed2-96e0-41dc-8844-ae33ebab5131">

<img width="1140" alt="Screenshot 2024-04-09 at 6 24 33 PM" src="https://github.com/tenstorrent-metal/tt-metal/assets/29221091/2f24e16d-08ba-416f-ac9d-758cc78949b6">


Also, the reason for the failure of acosh and logit op is that, nan cannot be stored in WHB0  as discussed here

https://github.com/tenstorrent-metal/tt-metal/issues/4409#issuecomment-1863973145

@cfjchu Can you check and close this issue?

@jliangTT Your comments please

**Comment by jliangTT** [comment]
@umadevimcw, is there anyway to to enable acosh and logit to test for non-nan scenarios?

**Comment by cfjchu** [comment]
Can you please submit a PR so we can verify this on our CI runners?

**Comment by umadevimcw** [comment]
> @umadevimcw, is there anyway to to enable acosh and logit to test for non-nan scenarios?

@jliangTT and @cfjchu we can do this. I will raise the PR with the updated test files, trigger CI runs and share the links here

**Comment by umadevimcw** [comment]
@jliangTT and @cfjchu 
This is the environment I am testing for wormhole where the tests are passing

<img width="1512" alt="image" src="https://github.com/tenstorrent-metal/tt-metal/assets/29221091/2dfad7c8-43ae-4378-a746-0f5e0dffb126">

But in CI it is failing

PR: #7403 


https://github.com/tenstorrent-metal/tt-metal/actions/runs/8658067193/job/23741361600

**Comment by umadevimcw** [comment]
<img width="1512" alt="Screenshot 2024-04-12 at 3 23 03 PM" src="https://github.com/tenstorrent-metal/tt-metal/assets/29221091/31c2dbb1-882a-42f4-934a-754c0e78bc71">
<img width="1512" alt="Screenshot 2024-04-12 at 3 24 22 PM" src="https://github.com/tenstorrent-metal/tt-metal/assets/29221091/9cfb646f-c0ea-4a0e-ab57-e17f1e38549e">


<img width="1512" alt="Screenshot 2024-04-12 at 3 26 30 PM" src="https://github.com/tenstorrent-metal/tt-metal/assets/29221091/4b9ba2a9-48cf-4c82-949d-17b8a288189f">


<img width="1512" alt="Screenshot 2024-04-12 at 3 26 55 PM" src="https://github.com/tenstorrent-metal/tt-metal/assets/29221091/7c35fbbe-9750-443e-be3a-c2225e549fac">

<img width="1512" alt="Screenshot 2024-04-12 at 3 27 33 PM" src="https://github.com/tenstorrent-metal/tt-metal/assets/29221091/c699b36c-38e9-441f-9e1f-edd2ce85c20c">

**Comment by umadevimcw** [comment]
@cfjchu Is it possible for you to check on WHB0 VM on your side? As I was not able to reproduce the error in the WHB0 VM that we are using.

**Comment by umadevimcw** [comment]
@cfjchu We checked with the WHB0 except `acosh` and `logit` op rest of the tests are passing.

**Comment by umadevimcw** [comment]
@cfjchu Also `acosh` and `logit` failed due to hardware limitations. you can read the comments in these two issues about storing nan and inf
https://github.com/tenstorrent/tt-metal/issues/8945
https://github.com/tenstorrent/tt-metal/issues/8944

**Comment by umadevimcw** [comment]
@cfjchu Above issues are no longer occurring in `N300` but I am getting the low pcc issue in `N150` Will debug that, but the issue with respect to `acosh` and `logit` are fixed and it is available in this PR(due to hardware limitations nan/inf are replaced with the numbers)
https://github.com/tenstorrent/tt-metal/pull/11243 
Kindly review it?

**Comment by umadevimcw** [comment]
@eyonland In this issue `acosh` and `logit` are fixed and merged to main.

All other reduction-based ops tests are `test_min,py` `test_mean.py`  `test_reduction.py`  and `test_sum.py` failing especially on WHB0 n150 only, but the same code in passing in WHB0 n300

**Comment by eyonland** [comment]
@tarafdarTT , would you take a look at these?  It looks like these reaming issues are part of the reduce op and that it may not be properly handling n150.

**Comment by VirdhatchaniKN** [comment]
STATUS : 

- Ops `acosh` and `logit` are fixed.
- All other reduction-based ops tests are `test_min.py`,  `test_mean.py`, `test_reduction.py `and `test_sum.py` failing especially on WHB0 N150 only, but the same code in passing in WHB0 N300. We observed that the output of the reduce op is not correct in WHB0 N150, Half of the data is always zero

**Comment by umadevimcw** [comment]
@eyonland @bbradelTT In a recent test run, I executed the following files: test_min.py, test_mean.py, test_reduction.py, and test_sum.py, and all the tests passed. However, when I triggered the CI pipeline, it failed again. To troubleshoot, I ran the same command used in CI locally:


```
pytest tests/ttnn/unit_tests -xv --splits 6 --group 2 -m "not disable_fast_runtime_mode"

```

This command caused the tests to fail. After the failure, I noticed that even when running test_mean.py individually, it was failing. To resolve this, I reset the card and reran the individual tests, and they passed.

Running `test_mean.py or test_min.py` after executing `test_maxpool2d.py` leads to test failures in CI. To mitigate this issue and avoid CI failures, I renamed these files and updated the PR #14669  so that these tests are moved to a different group. In this PPR there is no CI failures

**Comment by umadevimcw** [comment]
@bbradelTT We can reproduce the error by running 

`pytest tests/ttnn/unit_tests/operations/test_maxpool2d.py` first and then

`pytest tests/ttnn/unit_tests/operations/test_mean.py`

**Comment by eyonland** [comment]
@bbradelTT , this problem where the maxpool leaves the state of the device such that the next op (in this case the reduce op) does not work correctly sounds a lot like the bug in WH mentioned here #13569.   @yan-zaretskiy can give more details on this but it sounded like a register is not being properly cleared.

**Comment by umadevimcw** [comment]
> [@bbradelTT](https://github.com/bbradelTT) We can reproduce the error by running
> 
> `pytest tests/ttnn/unit_tests/operations/test_maxpool2d.py` first and then
> 
> `pytest tests/ttnn/unit_tests/operations/test_mean.py`

`test_mean.py` is renamed to `test_reduction_mean.py`

**Comment by bbradelTT** [comment]
Minimum example:
tt-smi reset then run the following via python test_pool.py

test_pool.py
```
import torch
import ttnn
from models.utility_functions import torch_random, comp_allclose
from tests.ttnn.utils_for_testing import assert_with_pcc


def test_maxpool(device, input_shape, kernel_size, stride, padding, dilation):
    torch_input = torch.rand(input_shape, dtype=torch.bfloat16)
    batch_size, in_c, in_h, in_w = input_shape

    input_tensor = torch.permute(torch_input, (0, 2, 3, 1))
    input_tensor = torch.reshape(input_tensor, (1, 1, -1, in_c))
    input_tensor = ttnn.from_torch(input_tensor, layout=ttnn.ROW_MAJOR_LAYOUT, device=device)
    output_tensor = ttnn.max_pool2d(
        input_tensor,
        batch_size,
        in_h,
        in_w,
        in_c,
        kernel_size,
        stride,
        padding,
        dilation,
    )

    expected_output = torch.nn.functional.max_pool2d(torch_input, kernel_size, stride, padding)

    output_tensor = ttnn.to_torch(output_tensor)
    _, out_c, out_h, out_w = expected_output.shape
    output_tensor = torch.reshape(output_tensor, (batch_size, out_h, out_w, out_c))
    output_tensor = torch.permute(output_tensor, (0, 3, 1, 2))

    assert torch.allclose(output_tensor, expected_output), "mismatch"


def test_global_avg_pool(device, input_shape):
    torch_input_tensor = torch.randn(input_shape, dtype=torch.bfloat16)
    torch_input_tensor = torch.ones(input_shape, dtype=torch.bfloat16)
    torch_output_tensor = torch.nn.functional.adaptive_avg_pool2d(torch_input_tensor, (1, 1))

    input_tensor = torch.permute(torch_input_tensor, (0, 2, 3, 1))
    input_tensor = ttnn.from_torch(input_tensor, layout=ttnn.TILE_LAYOUT, device=device)
    output_tensor = ttnn.global_avg_pool2d(input_tensor)
    #print(f'{input_tensor}\n{output_tensor}\ntot{torch_output_tensor}')
    output_tensor = ttnn.to_torch(output_tensor)
    output_tensor = torch.permute(output_tensor, (0, 3, 1, 2))

    assert_with_pcc(torch_output_tensor, output_tensor)

def test_mean(device, batch_size, h, w, dim):
    torch.manual_seed(0)

    torch_input_tensor = torch_random((batch_size, h, w), -1, 1, dtype=torch.bfloat16)
    torch_output_tensor = torch.mean(torch_input_tensor, dim=dim, keepdim=True, dtype=torch.bfloat16)

    input_tensor = ttnn.from_torch(torch_input_tensor, layout=ttnn.TILE_LAYOUT, device=device)

    output_tensor = ttnn.mean(input_tensor, dim=dim)
    output_tensor = ttnn.to_torch(output_tensor)
    assert_with_pcc(torch_output_tensor, output_tensor)

if __name__ == "__main__":
    try:
        device = ttnn.open_device(device_id=0, l1_small_size=4096)
        test_maxpool(device, (1, 192, 56, 56), (2, 2), (2, 2), (0, 0), (1, 1))
        #test_global_avg_pool(device, (1, 64, 1, 32))
        test_mean(device, 1, 32, 32, -2)
    finally:
        ttnn.close_device(device)
```

generated/watcher/kernel_names.txt
```
0: blank
1: tt_metal/impl/dispatch/kernels/cq_prefetch.cpp
2: tt_metal/impl/dispatch/kernels/cq_dispatch.cpp
3: tt_metal/impl/dispatch/kernels/cq_dispatch_slave.cpp
4: ttnn/cpp/ttnn/operations/reduction/generic/device/kernels/dataflow/reader_unary_transpose_wh_interleaved_input_cols_partitioned.cpp
5: ttnn/cpp/ttnn/operations/eltwise/unary/device/kernels/dataflow/writer_unary_interleaved_start_id.cpp
6: ttnn/cpp/ttnn/operations/reduction/generic/device/kernels/compute/reduce_h.cpp
7: ttnn/cpp/ttnn/operations/data_movement/sharded/device/kernels/dataflow/reader_unary_stick_layout_sharded_blocks_interleaved_start_id.cpp
8: ttnn/cpp/ttnn/operations/data_movement/sharded/device/kernels/dataflow/writer_unary_sharded.cpp
9: ttnn/cpp/ttnn/operations/data_movement/untilize_with_halo_v2/device/kernels/dataflow/halo_gather.cpp
10: ttnn/cpp/ttnn/operations/data_movement/untilize_with_halo_v2/device/kernels/dataflow/halo_gather.cpp
11: ttnn/cpp/ttnn/operations/pool/generic/device/kernels/dataflow/reader_max_pool_2d_multi_core_sharded_with_halo_v2.cpp
12: ttnn/cpp/ttnn/operations/pool/generic/device/kernels/dataflow/reader_max_pool_2d_multi_core_sharded_with_halo_v2.cpp
13: ttnn/cpp/ttnn/operations/pool/generic/device/kernels/compute/max_pool_multi_core.cpp
14: ttnn/cpp/ttnn/operations/reduction/generic/device/kernels/dataflow/reader_unary_transpose_wh_interleaved_input_cols_partitioned.cpp
15: ttnn/cpp/ttnn/operations/eltwise/unary/device/kernels/dataflow/writer_unary_interleaved_start_id.cpp
16: ttnn/cpp/ttnn/operations/reduction/generic/device/kernels/compute/reduce_h.cpp
```

Output:
```
Running First Mean
Got here. PCC is okay.
Running maxpool
Running Second Mean
Traceback (most recent call last):
  File "run_pool.py", line 58, in <module>
    test_mean(device, 1, 32, 32, -2)
  File "run_pool.py", line 46, in test_mean
    assert_with_pcc(torch_output_tensor, output_tensor)
  File "/proj_sw/user_dev/bbradel/tt-metal/tests/ttnn/utils_for_testing.py", line 57, in assert_with_pcc
    assert pcc_passed, construct_pcc_assert_message(pcc_message, expected_pytorch_result, actual_pytorch_result)
AssertionError: 0.712975805693972
```

**Comment by bbradelTT** [comment]
@ncvetkovicTT I'll try to isolate what is causing the problem. Feels like something in the inits.

**Comment by bbradelTT** [comment]
I tried making changes to ttnn/cpp/ttnn/operations/pool/generic/device/kernels/compute/max_pool_multi_core.cpp

After adding
```
    tilize_uninit(in_cb_id,out_cb_id);
    pack_untilize_uninit(out_cb_id);
```
the PCC is still bad on the second call.

After commenting out
```
    pack_untilize_dst_init_short<in_ntiles_c>(
        out_cb_id, num_out_rows, num_faces_in_tile); /* pack 1 row (1x16 or 1x32) */
```
the PCC is good on the second call.

**Comment by bbradelTT** [comment]
Related to https://github.com/tenstorrent/tt-metal/issues/15824

**Comment by bbradelTT** [comment]
Narrowed it down further:

Commented out

tt_metal/include/compute_kernel_api/pack_untilize.h
```
    PACK((llk_pack_untilize_init<block_ct_dim, full_ct_dim, diagonal, narrow_row, row_num_datums>(
        ocb, face_r_dim, num_faces)));
```
and reduce worked.

**Comment by prajaramanTT** [comment]
@bbradelTT Is this still an open issue ? If not, can you please mark this closed ? Thanks.

**Comment by ncvetkovicTT** [comment]
@prajaramanTT It is still open, being tracked together with #15824

**Comment by bbradelTT** [comment]
@ncvetkovicTT All the other stuff has been dealt with beforehand.  Does the minimum example in https://github.com/tenstorrent/tt-metal/issues/6991#issuecomment-2559885872 pass now? If yes, we can close this.

**Comment by ncvetkovicTT** [comment]
Yes, (1, 192, 56, 56) passes.
