### ISSUE TITLE
[Bug Report] ttnn.zeros crashes if input shape is 1D

### ISSUE THREAD

**Issue by marty1885** [tenstorrent/tt-metal#7008]
**Describe the bug**
`ttnn.zeros` crash the entire program if shape is 1D. However 2D is fine

**To Reproduce**

The following code demonstrates the issue on my computer

```python
import ttnn
device = ttnn.open_device(device_id=0)
zero = ttnn.zeros((32,), device=device)
```

With log
```
2024-04-02 14:06:41.380 | INFO     | ttnn:<module>:84 - Initial ttnn.CONFIG:
{'cache_path': PosixPath('/home/marty/.cache/ttnn'),
 'comparison_mode_pcc': 0.9999,
 'enable_buffer_report': False,
 'enable_comparison_mode': False,
 'enable_fast_runtime_mode': False,
 'enable_graph_report': False,
 'enable_logging': False,
 'enable_model_cache': False,
 'enable_tensor_report': False,
 'model_cache_path': PosixPath('/home/marty/.cache/ttnn/models'),
 'reports_path': PosixPath('generated/ttnn/reports'),
 'sqlite_db_path': PosixPath('generated/ttnn/reports/sqlite.db'),
 'throw_exception_on_fallback': False,
 'tmp_dir': PosixPath('/tmp/ttnn')}
                 Device | INFO     | Opening user mode device driver
2024-04-02 14:06:42.289 | INFO     | SiliconDriver   - Detected 1 PCI device : {0}
                  Metal | INFO     | Initializing device 0
                  Metal | INFO     | AI CLK for device 0 is:   1300 MHz
                 Always | FATAL    | Index is out of bounds for the rank, should be between 0 and 0 however is 18446744073709551615
Traceback (most recent call last):
  File "/home/marty/Documents/ttRWKV/main.py", line 3, in <module>
    zero = ttnn.zeros((32,), device=device)
  File "/home/marty/Documents/not-my-projects/tt-metal/ttnn/ttnn/decorators.py", line 390, in __call__
    output = self.decorated_function(*function_args, **function_kwargs)
  File "/home/marty/Documents/not-my-projects/tt-metal/ttnn/ttnn/decorators.py", line 322, in call_wrapper
    output = decorated_function(*function_args, **function_kwargs)
  File "/home/marty/Documents/not-my-projects/tt-metal/ttnn/ttnn/decorators.py", line 231, in call_wrapper
    return function(*function_args, **function_kwargs)
  File "/home/marty/Documents/not-my-projects/tt-metal/ttnn/ttnn/operations/creation.py", line 197, in zeros
    output_tensor = ttnn.experimental.tensor.zeros(
  File "/home/marty/Documents/not-my-projects/tt-metal/ttnn/ttnn/decorators.py", line 390, in __call__
    output = self.decorated_function(*function_args, **function_kwargs)
  File "/home/marty/Documents/not-my-projects/tt-metal/ttnn/ttnn/decorators.py", line 322, in call_wrapper
    output = decorated_function(*function_args, **function_kwargs)
  File "/home/marty/Documents/not-my-projects/tt-metal/ttnn/ttnn/decorators.py", line 231, in call_wrapper
    return function(*function_args, **function_kwargs)
RuntimeError: TT_ASSERT @ tt_eager/tensor/types.cpp:128: normalized_index >= 0 and normalized_index < rank
info:
Index is out of bounds for the rank, should be between 0 and 0 however is 18446744073709551615
backtrace:
 --- tt::tt_metal::Shape::operator[](long) const
 --- /home/marty/Documents/not-my-projects/tt-metal/tt_eager/tt_lib/_C.so(+0x9e6492) [0x7db1bfbe6492]
 --- /home/marty/Documents/not-my-projects/tt-metal/tt_eager/tt_lib/_C.so(+0x9e80b9) [0x7db1bfbe80b9]
 --- /home/marty/Documents/not-my-projects/tt-metal/tt_eager/tt_lib/_C.so(+0x9cc52f) [0x7db1bfbcc52f]
 --- tt::tt_metal::tensor_impl::to_device_wrapper(tt::tt_metal::Tensor const&, tt::tt_metal::Device*, tt::tt_metal::MemoryConfig const&, std::optional<std::reference_wrapper<tt::tt_metal::CommandQueue> >)
 --- /home/marty/Documents/not-my-projects/tt-metal/tt_eager/tt_lib/_C.so(+0x9a9181) [0x7db1bfba9181]
 --- tt::tt_metal::Tensor::to(tt::tt_metal::Device*, tt::tt_metal::MemoryConfig const&) const
 --- /home/marty/Documents/not-my-projects/tt-metal/tt_eager/tt_lib/_C.so(+0x762e84) [0x7db1bf962e84]
 --- tt::tt_metal::full(tt::tt_metal::Shape, float, tt::tt_metal::DataType, tt::tt_metal::Layout, tt::tt_metal::Device*, tt::tt_metal::MemoryConfig const&)
 --- tt::tt_metal::zeros(tt::tt_metal::Shape, tt::tt_metal::DataType, tt::tt_metal::Layout, tt::tt_metal::Device*, tt::tt_metal::MemoryConfig const&)
 --- /home/marty/Documents/not-my-projects/tt-metal/tt_eager/tt_lib/_C.so(+0x2898fd) [0x7db1bf4898fd]
 --- /home/marty/Documents/not-my-projects/tt-metal/tt_eager/tt_lib/_C.so(+0x1d4fe6) [0x7db1bf3d4fe6]
 --- python(+0x14bb15) [0x614714124b15]
 --- python(PyObject_Call+0x1fe) [0x61471412216e]
 --- python(_PyEval_EvalFrameDefault+0x5dec) [0x6147141c285c]
 --- python(_PyFunction_Vectorcall+0x9eb) [0x61471419f94b]
 --- python(PyObject_Call+0xb8) [0x614714122028]
 --- python(_PyEval_EvalFrameDefault+0x2c0b) [0x6147141bf67b]
 --- python(_PyFunction_Vectorcall+0x9eb) [0x61471419f94b]
 --- python(PyObject_Call+0xb8) [0x614714122028]
 --- python(_PyEval_EvalFrameDefault+0x2c0b) [0x6147141bf67b]
 --- python(_PyFunction_Vectorcall+0x25d) [0x61471419f1bd]
 --- python(_PyObject_FastCallDictTstate+0xd8) [0x614714124e08]
 --- python(_PyObject_Call_Prepend+0x6a) [0x61471412757a]
 --- python(+0x257b95) [0x614714230b95]
 --- python(_PyObject_MakeTpCall+0x1ea) [0x61471411bafa]
 --- python(_PyEval_EvalFrameDefault+0x5954) [0x6147141c23c4]
 --- python(_PyFunction_Vectorcall+0x9eb) [0x61471419f94b]
 --- python(PyObject_Call+0xb8) [0x614714122028]
 --- python(_PyEval_EvalFrameDefault+0x2c0b) [0x6147141bf67b]
 --- python(_PyFunction_Vectorcall+0x9eb) [0x61471419f94b]
 --- python(PyObject_Call+0xb8) [0x614714122028]
 --- python(_PyEval_EvalFrameDefault+0x2c0b) [0x6147141bf67b]
 --- python(_PyFunction_Vectorcall+0x9eb) [0x61471419f94b]
 --- python(PyObject_Call+0xb8) [0x614714122028]
 --- python(_PyEval_EvalFrameDefault+0x2c0b) [0x6147141bf67b]
 --- python(_PyFunction_Vectorcall+0x25d) [0x61471419f1bd]
 --- python(_PyObject_FastCallDictTstate+0xd8) [0x614714124e08]
 --- python(_PyObject_Call_Prepend+0x6a) [0x61471412757a]
 --- python(+0x257b95) [0x614714230b95]
 --- python(_PyObject_MakeTpCall+0x1ea) [0x61471411bafa]
 --- python(_PyEval_EvalFrameDefault+0x5954) [0x6147141c23c4]
 --- python(+0x1c51b9) [0x61471419e1b9]
 --- python(PyEval_EvalCode+0x87) [0x614714251f67]
 --- python(+0x279029) [0x614714252029]
 --- python(+0x29ec94) [0x614714277c94]
 --- python(+0x2a5149) [0x61471427e149]
 --- python(_PyRun_SimpleFileObject+0x1af) [0x61471427e2ff]
 --- python(_PyRun_AnyFileObject+0x43) [0x61471427e403]
 --- python(Py_RunMain+0x398) [0x61471427f318]
 --- python(Py_BytesMain+0x39) [0x61471427f469]
 --- /usr/lib/libc.so.6(+0x25cd0) [0x7db1c12cccd0]
 --- /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7db1c12ccd8a]
 --- python(+0x2112d1) [0x6147141ea2d1]

                 Device | INFO     | Closing user mode device drivers
                 Always | FATAL    | Process tear down with device 0 still active
terminate called after throwing an instance of 'std::runtime_error'
  what():  TT_THROW @ tt_metal/impl/device/device.cpp:35: tt::exception
info:
Process tear down with device {} still active
0
backtrace:
 --- /usr/lib/libc.so.6(+0x3eb36) [0x7db1c12e5b36]
 --- /usr/lib/libc.so.6(+0x3ec80) [0x7db1c12e5c80]
 --- /usr/lib/libc.so.6(+0x25cd7) [0x7db1c12cccd7]
 --- /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7db1c12ccd8a]
 --- python(+0x2112d1) [0x6147141ea2d1]

[1]    47537 IOT instruction (core dumped)  python main.py

```

**Expected behavior**
The code snippet should not crash. If 1D tensors are not supported. Should report as such instead of printing error that indicates error.

**Please complete the following environment information:**
- OS: Arch Linux
- Version of software: 96357b6f8324743e554fb21534b4d8afbd955810

**Additional context**

**Comment by marty1885** [comment]
Found in documents

```
 A TT Tensor of shape [W, Z, Y, X] can have TILE layout only if both X and Y are divisible by 2.
```

How can we do batch=1 inference in that case?

**Comment by jliangTT** [comment]
@eyonland , do you mind help triage this? seems like an egregious error.

**Comment by jliangTT** [comment]
@arakhmati , is this done?

**Comment by arakhmati** [comment]
The problem was fixed by setting default layout to ROW_MAJOR. Closing the issue
