### ISSUE TITLE
Falcon40B gets op mismatch error with program_cache runs

### ISSUE THREAD

**Issue by mo-tenstorrent** [tenstorrent/tt-metal#7546]
```
export WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml
python -m tracy -r -m pytest models/demos/falcon40b/tests/test_falcon_decoder.py -k \"enable_program_cache and 8chips and prefill_seq2048 and BFLOAT8_B-DRAM\"
```

reports op mismatch error: 
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/mmemarian/tt-metal/tt_eager/tracy.py", line 325, in <module>
    main()
  File "/home/mmemarian/tt-metal/tt_eager/tracy.py", line 309, in main
    generate_report(options.output_folder, options.name_append)
  File "/home/mmemarian/tt-metal/tt_eager/tracy.py", line 158, in generate_report
    process_ops(outFolder, nameAppend, True)
  File "/home/mmemarian/tt-metal/tt_metal/tools/profiler/process_ops_logs.py", line 392, in process_ops
    deviceOps = append_device_data(ops, PROFILER_LOGS_DIR)
  File "/home/mmemarian/tt-metal/tt_metal/tools/profiler/process_ops_logs.py", line 162, in append_device_data
    assert len(deviceOps[device]) == len(
AssertionError: Device data mismatch. Expected 363 but received 48 ops on device 0
```

This is on T3K and is 100% reproducible and reports the same number of expected and received ops.

**Comment by mo-tenstorrent** [comment]
@s-jovic

**Comment by mo-tenstorrent** [comment]
Confirmed 
```
python -m tracy --no-op-info-cache -r -m pytest models/demos/falcon40b/tests/test_falcon_decoder.py -k \"enable_program_cache and 8chips and prefill_seq2048 and BFLOAT8_B-DRAM\"
```
runs fine. 

this means the error is due to a hashing clash

**Comment by mo-tenstorrent** [comment]
Confirmed  with @arakhmati that by design program hash does not take device id into account. 

Op profiler should also run a map per device.
