### ISSUE TITLE
Segfault in `enqueue_read_buffer` with FD2.0

### ISSUE THREAD

**Issue by cglagovichTT** [tenstorrent/tt-metal#8163]
## Issue
Sefault in `enqueue_read_buffer` with FD2.0.

## Repro

- branch: [`model-team/perf-fd2`](https://github.com/tenstorrent/tt-metal/tree/model-team/perf-fd2) contains debug prints in `enqueue_read_buffer` from @tt-asaigal 
- synchronous queues
- 1GHz
```
python -m tracy -r -v -p --no-op-info-cache -m pytest  -svv models/experimental/llama2_70b/tests/test_llama_model.py::test_LlamaModel_inference[prefill_2k-8chip-T3000-1L]
```

## Expected Output
```
  58.73 Kbps / 31.9% =   0.18 Mbps | Tx: 3236.35 KB | 65.38 MB | 2:36.4Calling: enqueue_read_buffer
interleaved read cmd 25654624
Fatal Python error: Segmentation fault

Thread 0x00007f4b0bff7700 (most recent call first):
  File "/usr/lib/python3.8/threading.py", line 306 in wait
  File "/usr/lib/python3.8/threading.py", line 558 in wait
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/tqdm/_monitor.py", line 60 in run
  File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap

Current thread 0x00007f4f0fb94740 (most recent call first):
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/_io/saferepr.py", line 76 in repr_instance
  File "/usr/lib/python3.8/reprlib.py", line 62 in repr1
  File "/usr/lib/python3.8/reprlib.py", line 71 in <listcomp>
  File "/usr/lib/python3.8/reprlib.py", line 71 in _repr_iterable
  File "/usr/lib/python3.8/reprlib.py", line 81 in repr_list
  File "/usr/lib/python3.8/reprlib.py", line 60 in repr1
  File "/usr/lib/python3.8/reprlib.py", line 52 in repr
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/_io/saferepr.py", line 64 in repr
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/_io/saferepr.py", line 115 in saferepr
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/_code/code.py", line 731 in repr_args
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/_code/code.py", line 821 in repr_traceback_entry
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/_code/code.py", line 871 in repr_traceback
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/_code/code.py", line 944 in repr_excinfo
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/_code/code.py", line 669 in getrepr
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/nodes.py", line 484 in _repr_failure_py
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/python.py", line 1823 in repr_failure
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/reports.py", line 349 in from_item_and_call
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/runner.py", line 366 in pytest_runtest_makereport
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/runner.py", line 222 in call_and_report
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/runner.py", line 131 in runtestprotocol
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/runner.py", line 112 in pytest_runtest_protocol
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/main.py", line 349 in pytest_runtestloop
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/main.py", line 324 in _main
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/main.py", line 270 in wrap_session
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/main.py", line 317 in pytest_cmdline_main
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/config/__init__.py", line 167 in main
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/config/__init__.py", line 190 in console_main
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/pytest/__main__.py", line 5 in <module>
  File "/usr/lib/python3.8/runpy.py", line 87 in _run_code
  File "/usr/lib/python3.8/runpy.py", line 210 in run_module
  File "<string>", line 1 in <module>
  File "/home/cglagovich/tt-metal/tt_eager/tracy.py", line 76 in runctx
  File "/home/cglagovich/tt-metal/tt_eager/tracy.py", line 272 in main
  File "/home/cglagovich/tt-metal/tt_eager/tracy.py", line 325 in <module>
  File "/usr/lib/python3.8/runpy.py", line 87 in _run_code
  File "/usr/lib/python3.8/runpy.py", line 194 in _run_module_as_main  58.73 Kbps / 31.9% =   0.18 Mbps | Tx: 3236.35 KB | 65.38 MB | 2:36.4Calling: enqueue_read_buffer
interleaved read cmd 25654624
Fatal Python error: Segmentation fault

Thread 0x00007f4b0bff7700 (most recent call first):
  File "/usr/lib/python3.8/threading.py", line 306 in wait
  File "/usr/lib/python3.8/threading.py", line 558 in wait
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/tqdm/_monitor.py", line 60 in run
  File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap

Current thread 0x00007f4f0fb94740 (most recent call first):
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/_io/saferepr.py", line 76 in repr_instance
  File "/usr/lib/python3.8/reprlib.py", line 62 in repr1
  File "/usr/lib/python3.8/reprlib.py", line 71 in <listcomp>
  File "/usr/lib/python3.8/reprlib.py", line 71 in _repr_iterable
  File "/usr/lib/python3.8/reprlib.py", line 81 in repr_list
  File "/usr/lib/python3.8/reprlib.py", line 60 in repr1
  File "/usr/lib/python3.8/reprlib.py", line 52 in repr
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/_io/saferepr.py", line 64 in repr
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/_io/saferepr.py", line 115 in saferepr
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/_code/code.py", line 731 in repr_args
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/_code/code.py", line 821 in repr_traceback_entry
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/_code/code.py", line 871 in repr_traceback
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/_code/code.py", line 944 in repr_excinfo
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/_code/code.py", line 669 in getrepr
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/nodes.py", line 484 in _repr_failure_py
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/python.py", line 1823 in repr_failure
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/reports.py", line 349 in from_item_and_call
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/runner.py", line 366 in pytest_runtest_makereport
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/runner.py", line 222 in call_and_report
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/runner.py", line 131 in runtestprotocol
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/runner.py", line 112 in pytest_runtest_protocol
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/main.py", line 349 in pytest_runtestloop
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/main.py", line 324 in _main
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/main.py", line 270 in wrap_session
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/main.py", line 317 in pytest_cmdline_main
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/config/__init__.py", line 167 in main
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/config/__init__.py", line 190 in console_main
  File "/home/cglagovich/tt-metal/build/python_env/lib/python3.8/site-packages/pytest/__main__.py", line 5 in <module>
  File "/usr/lib/python3.8/runpy.py", line 87 in _run_code
  File "/usr/lib/python3.8/runpy.py", line 210 in run_module
  File "<string>", line 1 in <module>
  File "/home/cglagovich/tt-metal/tt_eager/tracy.py", line 76 in runctx
  File "/home/cglagovich/tt-metal/tt_eager/tracy.py", line 272 in main
  File "/home/cglagovich/tt-metal/tt_eager/tracy.py", line 325 in <module>
  File "/usr/lib/python3.8/runpy.py", line 87 in _run_code
  File "/usr/lib/python3.8/runpy.py", line 194 in _run_module_as_main
```

tt-smi reset fails
```
(venv) cglagovich@sjc-snva-t3002:~/tt-metal/scripts/install$ tt-smi -r 0,1,2,3
 Starting pci link reset on WH devices at pci indices: 0, 1, 2, 3
Traceback (most recent call last):
  File "/home/cglagovich/tt-metal/scripts/install/venv/bin/tt-smi", line 8, in <module>
    sys.exit(main())
  File "/home/cglagovich/tt-metal/scripts/install/venv/lib/python3.8/site-packages/tt_smi/tt_smi.py", line 733, in main
    pci_board_reset(args.reset, reinit=True)
  File "/home/cglagovich/tt-metal/scripts/install/venv/lib/python3.8/site-packages/tt_smi/tt_smi_backend.py", line 544, in pci_board_reset
    reset_devices = WHChipReset().full_lds_reset(pci_interfaces=reset_wh_pci_idx)
  File "/home/cglagovich/tt-metal/scripts/install/venv/lib/python3.8/site-packages/tt_tools_common/reset_common/wh_reset.py", line 83, in full_lds_reset
    refclk_list.append(read_refclk_counter(chip))
  File "/home/cglagovich/tt-metal/scripts/install/venv/lib/python3.8/site-packages/tt_tools_common/utils_common/tools_utils.py", line 189, in read_refclk_counter
    high1 = chip.axi_read32(high_addr)
Exception: Read 0xffffffff from ARC scratch[6]: you should reset the board.
```

**Comment by cglagovichTT** [comment]
Plan:
1. Give Daniel Rosen time to debug the tt-smi reset issue
2. Repro without profiling

**Comment by cglagovichTT** [comment]
Saw this with prefill-2k but not prefill-128. Possible issue with the size of a read command?
Prefill-2k will read `2048 x 1024` BF16 datums from each device

**Comment by cglagovichTT** [comment]
FYI this took down the cards and likely requires a cold reboot

**Comment by cglagovichTT** [comment]
i'll try to repro again on my machine tonight. I only reproed the one time, so idk if ND

**Comment by aliuTT** [comment]
@cglagovichTT are you able to consistently repro on your machine? If so, I may need to hop onto your machine to continue debugging. Also, are you blocked by this issue? If not, can we downgrade to a P1?

**Comment by cglagovichTT** [comment]
let's downgrade - i was put on something else for now so it might be a few days before i can repro

**Comment by pgkeller** [comment]
@cglagovichTT ping

**Comment by cglagovichTT** [comment]
I am not able to repro this segfault on main. Closing
