### ISSUE TITLE
With FD2.0 perf report can fail on wrong device op counts

### ISSUE THREAD

**Issue by mo-tenstorrent** [tenstorrent/tt-metal#8165]
@cglagovichTT provided the following info and log files on the fail:

```
2024-05-06 13:54:00.661 | INFO     | tt_metal.tools.profiler.process_device_log:core_to_device_timeseries:352 - Importing Data For Device Number : 0
2024-05-06 13:54:00.860 | INFO     | tt_metal.tools.profiler.process_device_log:core_to_device_timeseries:352 - Importing Data For Device Number : 7
2024-05-06 13:54:00.910 | INFO     | tt_metal.tools.profiler.process_device_log:core_to_device_timeseries:352 - Importing Data For Device Number : 6
2024-05-06 13:54:00.961 | INFO     | tt_metal.tools.profiler.process_device_log:core_to_device_timeseries:352 - Importing Data For Device Number : 1
2024-05-06 13:54:01.013 | INFO     | tt_metal.tools.profiler.process_device_log:core_to_device_timeseries:352 - Importing Data For Device Number : 2
2024-05-06 13:54:01.254 | INFO     | tt_metal.tools.profiler.process_device_log:core_to_device_timeseries:352 - Importing Data For Device Number : 5
2024-05-06 13:54:01.305 | INFO     | tt_metal.tools.profiler.process_device_log:core_to_device_timeseries:352 - Importing Data For Device Number : 4
2024-05-06 13:54:01.359 | INFO     | tt_metal.tools.profiler.process_device_log:core_to_device_timeseries:352 - Importing Data For Device Number : 3
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/cglagovich/tt-metal/tt_eager/tracy.py", line 325, in <module>
    main()
  File "/home/cglagovich/tt-metal/tt_eager/tracy.py", line 309, in main
    generate_report(options.output_folder, options.name_append)
  File "/home/cglagovich/tt-metal/tt_eager/tracy.py", line 158, in generate_report
    process_ops(outFolder, nameAppend, True)
  File "/home/cglagovich/tt-metal/tt_metal/tools/profiler/process_ops_logs.py", line 400, in process_ops
    deviceOps = append_device_data(ops, PROFILER_LOGS_DIR)
  File "/home/cglagovich/tt-metal/tt_metal/tools/profiler/process_ops_logs.py", line 170, in append_device_data
    assert len(deviceOps[device]) == len(
AssertionError: Device data mismatch. Expected 57 but received 58 ops on device 0
```

[profiler.logs.zip](https://github.com/tenstorrent/tt-metal/files/15222600/profiler.logs.zip)

**Comment by mo-tenstorrent** [comment]
With FD2.0 it looks like `GO` message is shifted causing misaligned FW starts, making a single multi-core OP to look like multiple OPs 

![Image](https://github.com/tenstorrent/tt-metal/assets/109363418/fb02f0ce-9f5f-4172-88ce-151c72b3367c)

**Comment by cglagovichTT** [comment]
FYI @johanna-rock-tt @uaydonat

**Comment by aliuTT** [comment]
@mo-tenstorrent you mean the start time of go messages are shifted?

**Comment by mo-tenstorrent** [comment]
More info on the staggered start and how it can look like 2 back to back op starts

https://github.com/tenstorrent/tt-metal/assets/109363418/2c9d81a3-1b33-42e1-ad79-d3b486714396

Staggered start on ERISC looking like around 5us

![Image](https://github.com/tenstorrent/tt-metal/assets/109363418/c324f20f-ca77-4be3-81d3-b2d17dba8404)

**Comment by mo-tenstorrent** [comment]
Confirmed stagger start on all_gather unit test as well.

Test command: 
```
pytest tests/tt_eager/python_api_testing/unit_testing/misc/test_all_gather.py::test_all_gather_on_t3000_post_commit[mem_config0-input_dtype0-8-1-input_shape1-0-layout1]
```

This is still considered as one op by profiler as FW zones of the cores as still barely overlapping.

![Image](https://github.com/tenstorrent/tt-metal/assets/109363418/ba289b44-16c7-47fc-9d99-63507473570d)

**Comment by mo-tenstorrent** [comment]
@aliuTT Will be trying `write packed` to see if the stagger GO msg gets better.

**Comment by aliuTT** [comment]
Definitely less staggering but I still see core (1,1) BRISC starting after core (9,1) BRISC has finished. Is that going to be a problem?

![Image](https://github.com/tenstorrent/tt-metal/assets/130597713/d00533ec-8e6d-48e2-8ac7-53b311e180ea)

**Comment by aliuTT** [comment]
Just double checked, the staggering here makes sense, since the test is using 8 separate CoreRanges, each with one core. They are all different kernels, so this isn't really a multicast to 8 cores.

**Comment by davorchap** [comment]
@mo-tenstorrent is this resolved now, can we close?

**Comment by aliuTT** [comment]
I pushed go signal changes to main already. No more actionables on my end

**Comment by cglagovichTT** [comment]
I was able to collect device perf locally, I'm fine to close

**Comment by mo-tenstorrent** [comment]
Great, Closing this ticket. 

FYI: Assigning IDs to BRISC/ERISC FWs to determine OPs is tracked under : #3764
