### ISSUE TITLE
Mixtral MoE layer segfault 

### ISSUE THREAD

**Issue by sraizada-tt** [tenstorrent/tt-metal#8289]
Running MoE layer in loops (for 32*50 iterations), we see at segfault at a non-deterministic iteration number:
```
Fatal Python error: Segmentation fault

Current thread 0x00007f35368cf740 (most recent call first):
  File "/proj_sw/user_dev/sraizada/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/_io/saferepr.py", line 76 in repr_instance
  File "/usr/lib/python3.8/reprlib.py", line 62 in repr1
  File "/usr/lib/python3.8/reprlib.py", line 52 in repr
  File "/proj_sw/user_dev/sraizada/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/_io/saferepr.py", line 64 in repr
  File "/proj_sw/user_dev/sraizada/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/_io/saferepr.py", line 115 in saferepr
  File "/proj_sw/user_dev/sraizada/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/_code/code.py", line 731 in repr_args
  File "/proj_sw/user_dev/sraizada/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/_code/code.py", line 821 in repr_traceback_entry
  File "/proj_sw/user_dev/sraizada/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/_code/code.py", line 871 in repr_traceback
  File "/proj_sw/user_dev/sraizada/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/_code/code.py", line 944 in repr_excinfo
  File "/proj_sw/user_dev/sraizada/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/_code/code.py", line 669 in getrepr
  File "/proj_sw/user_dev/sraizada/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/nodes.py", line 484 in _repr_failure_py
  File "/proj_sw/user_dev/sraizada/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/python.py", line 1823 in repr_failure
  File "/proj_sw/user_dev/sraizada/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/reports.py", line 349 in from_item_and_call
  File "/proj_sw/user_dev/sraizada/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/runner.py", line 366 in pytest_runtest_makereport
  File "/proj_sw/user_dev/sraizada/tt-metal/build/python_env/lib/python3.8/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/proj_sw/user_dev/sraizada/tt-metal/build/python_env/lib/python3.8/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/proj_sw/user_dev/sraizada/tt-metal/build/python_env/lib/python3.8/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/proj_sw/user_dev/sraizada/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/runner.py", line 222 in call_and_report
  File "/proj_sw/user_dev/sraizada/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/runner.py", line 131 in runtestprotocol
  File "/proj_sw/user_dev/sraizada/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/runner.py", line 112 in pytest_runtest_protocol
  File "/proj_sw/user_dev/sraizada/tt-metal/build/python_env/lib/python3.8/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/proj_sw/user_dev/sraizada/tt-metal/build/python_env/lib/python3.8/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/proj_sw/user_dev/sraizada/tt-metal/build/python_env/lib/python3.8/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/proj_sw/user_dev/sraizada/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/main.py", line 349 in pytest_runtestloop
  File "/proj_sw/user_dev/sraizada/tt-metal/build/python_env/lib/python3.8/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/proj_sw/user_dev/sraizada/tt-metal/build/python_env/lib/python3.8/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/proj_sw/user_dev/sraizada/tt-metal/build/python_env/lib/python3.8/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/proj_sw/user_dev/sraizada/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/main.py", line 324 in _main
  File "/proj_sw/user_dev/sraizada/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/main.py", line 270 in wrap_session
  File "/proj_sw/user_dev/sraizada/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/main.py", line 317 in pytest_cmdline_main
  File "/proj_sw/user_dev/sraizada/tt-metal/build/python_env/lib/python3.8/site-packages/pluggy/_callers.py", line 103 in _multicall
  File "/proj_sw/user_dev/sraizada/tt-metal/build/python_env/lib/python3.8/site-packages/pluggy/_manager.py", line 120 in _hookexec
  File "/proj_sw/user_dev/sraizada/tt-metal/build/python_env/lib/python3.8/site-packages/pluggy/_hooks.py", line 513 in __call__
  File "/proj_sw/user_dev/sraizada/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/config/__init__.py", line 167 in main
  File "/proj_sw/user_dev/sraizada/tt-metal/build/python_env/lib/python3.8/site-packages/_pytest/config/__init__.py", line 190 in console_main
  File "/proj_sw/user_dev/sraizada/tt-metal/build/python_env/bin/pytest", line 8 in <module>
Segmentation fault (core dumped)
```

To reproduce (branch **mixtral-ttnn-mesh**): 
`pytest models/demos/t3000/mixtral8x7b/tests/test_moe.py`

**Comment by uaydonat** [comment]
@davorchap

**Comment by uaydonat** [comment]
This is when we remove (6,7) grid workaround.

**Comment by davorchap** [comment]
> This is when we remove (6,7) grid workaround.

Thanks. 

Is it deterministic?

Do we have the backtrace from gdb?

**Comment by sraizada-tt** [comment]
This is deterministic. I'll add the gdb backtrace shortly.

**Comment by sraizada-tt** [comment]
```
Traceback (most recent call last):
  File "models/demos/t3000/mixtral8x7b/tests/test_moe.py", line 218, in <module>
    test_moe()
  File "models/demos/t3000/mixtral8x7b/tests/test_moe.py", line 215, in test_moe
    output = model(inputs)
  File "/proj_sw/user_dev/sraizada/tt-metal/build/python_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/proj_sw/user_dev/sraizada/tt-metal/build/python_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "models/demos/t3000/mixtral8x7b/tests/test_moe.py", line 184, in forward
    weights_1SB1 = top_2(
  File "models/demos/t3000/mixtral8x7b/tests/test_moe.py", line 78, in top_2
    gate_logits_1SB8_masked = ttnn.where(cond0, top_2_mask, gate_logits_1SB8)
  File "/proj_sw/user_dev/sraizada/tt-metal/ttnn/ttnn/decorators.py", line 701, in __call__
    output = self.decorated_function(*function_args, **function_kwargs)
  File "/proj_sw/user_dev/sraizada/tt-metal/ttnn/ttnn/decorators.py", line 626, in call_wrapper
    output = decorated_function(*function_args, **function_kwargs)
  File "/proj_sw/user_dev/sraizada/tt-metal/ttnn/ttnn/decorators.py", line 411, in call_wrapper
    return function(*function_args, **function_kwargs)
  File "/proj_sw/user_dev/sraizada/tt-metal/ttnn/ttnn/operations/ternary.py", line 323, in ternary_function
    output_tensor = ttl_ternary_function(predicate, true_value, false_value, output_mem_config=memory_config)
RuntimeError: Read 0xffffffff from ARC scratch[6]: you should reset the board.
```

seems to be faulting at ttnn.where

**Comment by jliangTT** [comment]
@eyonland , can you determine if this is in the TTNN layer or in the op layers?

**Comment by yieldthought** [comment]
This is passing with our latest code (which uses a different top-2 implementation) even with an (8, 8) grid. We are not blocked by this. Would you like to keep the ticket open to fix the segfault or close it?
