### ISSUE TITLE
UBSan and ASan errors from dprint server

### ISSUE THREAD

**Issue by yan-zaretskiy** [tenstorrent/tt-metal#9419]
I compiled `tt-metal` with ASan and UBSan flags enabled and ran the `./tests/scripts/run_cpp_unit_tests.sh` script. I observe numerous reports from the dprint server code that are forth investigating. 

## Misaligned address loads

```
../tt_metal/impl/debug/dprint_server.cpp:761:31: runtime error: load of misaligned address 0x5110001a9f8b for type 'uint32_t' (aka 'unsigned int'), which requires 4 byte alignment
0x5110001a9f8b: note: pointer points here
 20  00 05 04 01 00 00 00 01  01 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00

../tt_metal/impl/debug/dprint_server.cpp:814:30: runtime error: load of misaligned address 0x51100020020e for type 'uint32_t' (aka 'unsigned int'), which requires 4 byte alignment
0x51100020020e: note: pointer points here
 00 00 0e 04 04 00  00 00 00 18 54 65 73 74  20 44 65 62 75 67 20 50  72 69 6e 74 3a 20 44 61  74 61
             ^ 
../tt_metal/impl/debug/dprint_server.cpp:778:31: runtime error: load of misaligned address 0x51100020073b for type 'int32_t' (aka 'int'), which requires 4 byte alignment
0x51100020073b: note: pointer points here
 0a  00 09 04 65 00 00 00 0b  04 bc 1a cf bf 0c 01 40  0f 02 fb 3d 01 01 00 03  01 65 04 02 2b 02 05
              ^ 
../tt_metal/impl/debug/dprint_server.cpp:786:31: runtime error: load of misaligned address 0x511000200741 for type 'float', which requires 4 byte alignment
0x511000200741: note: pointer points here
 00 00 0b  04 bc 1a cf bf 0c 01 40  0f 02 fb 3d 01 01 00 03  01 65 04 02 2b 02 05 04  40 e2 01 00 06
              ^ 
../tt_metal/impl/debug/dprint_server.cpp:765:31: runtime error: load of misaligned address 0x51100020075e for type 'uint64_t' (aka 'unsigned long'), which requires 8 byte alignment
0x51100020075e: note: pointer points here
 01 00 06 08 15 e7  cc 1f 02 00 00 00 01 01  00 07 01 ef 08 02 a9 fe  09 04 64 52 ff ff 0a 08  eb 40
             ^ 
../tt_metal/impl/debug/dprint_server.cpp:203:13: runtime error: member access within misaligned address 0x51100020098e for type 'TileSliceHostDev<0>', which requires 4 byte alignment
0x51100020098e: note: pointer points here
 00 00 17 54 40 a3  01 00 00 00 20 00 08 00  00 00 20 00 08 00 10 00  01 00 fb 3d 03 3e fb 3e  03 3f
             ^ 
../tt_metal/impl/debug/dprint_server.cpp:209:26: runtime error: member access within misaligned address 0x51100020098e for type 'TileSliceHostDev<0>', which requires 4 byte alignment
0x51100020098e: note: pointer points here
 00 00 17 54 40 a3  01 00 00 00 20 00 08 00  00 00 20 00 08 00 10 00  01 00 fb 3d 03 3e fb 3e  03 3f
             ^ 
../tt_metal/impl/debug/dprint_server.cpp:209:26: runtime error: load of misaligned address 0x511000200992 for type 'uint16_t' (aka 'unsigned short'), which requires 4 byte alignment
0x511000200992: note: pointer points here
 40 a3  01 00 00 00 20 00 08 00  00 00 20 00 08 00 10 00  01 00 fb 3d 03 3e fb 3e  03 3f 7b 3e 83 3e
              ^ 
../tt_metal/impl/debug/dprint_server.cpp:209:39: runtime error: member access within misaligned address 0x51100020098e for type 'TileSliceHostDev<0>', which requires 4 byte alignment
0x51100020098e: note: pointer points here
 00 00 17 54 40 a3  01 00 00 00 20 00 08 00  00 00 20 00 08 00 10 00  01 00 fb 3d 03 3e fb 3e  03 3f
             ^ 
../tt_metal/impl/debug/dprint_server.cpp:210:30: runtime error: member access within misaligned address 0x51100020098e for type 'TileSliceHostDev<0>', which requires 4 byte alignment
0x51100020098e: note: pointer points here
 00 00 17 54 40 a3  01 00 00 00 20 00 08 00  00 00 20 00 08 00 10 00  01 00 fb 3d 03 3e fb 3e  03 3f
             ^ 
../tt_metal/impl/debug/dprint_server.cpp:210:43: runtime error: member access within misaligned address 0x51100020098e for type 'TileSliceHostDev<0>', which requires 4 byte alignment
0x51100020098e: note: pointer points here
 00 00 17 54 40 a3  01 00 00 00 20 00 08 00  00 00 20 00 08 00 10 00  01 00 fb 3d 03 3e fb 3e  03 3f
             ^ 
../tt_metal/impl/debug/dprint_server.cpp:210:43: runtime error: load of misaligned address 0x51100020099a for type 'uint16_t' (aka 'unsigned short'), which requires 4 byte alignment
0x51100020099a: note: pointer points here
 08 00  00 00 20 00 08 00 10 00  01 00 fb 3d 03 3e fb 3e  03 3f 7b 3e 83 3e 7b 3f  83 3f fb 3f 03 40
              ^ 
../tt_metal/impl/debug/dprint_server.cpp:214:30: runtime error: member access within misaligned address 0x51100020098e for type 'TileSliceHostDev<0>', which requires 4 byte alignment
0x51100020098e: note: pointer points here
 00 00 17 54 40 a3  01 00 00 00 20 00 08 00  00 00 20 00 08 00 10 00  01 00 fb 3d 03 3e fb 3e  03 3f
             ^ 
../tt_metal/impl/debug/dprint_server.cpp:214:30: runtime error: load of misaligned address 0x51100020099e for type 'uint16_t' (aka 'unsigned short'), which requires 4 byte alignment
0x51100020099e: note: pointer points here
 20 00 08 00 10 00  01 00 fb 3d 03 3e fb 3e  03 3f 7b 3e 83 3e 7b 3f  83 3f fb 3f 03 40 fb 40  03 41
             ^ 
../tt_metal/impl/debug/dprint_server.cpp:218:49: runtime error: member access within misaligned address 0x51100020098e for type 'TileSliceHostDev<0>', which requires 4 byte alignment
0x51100020098e: note: pointer points here
 00 00 17 54 40 a3  01 00 00 00 20 00 08 00  00 00 20 00 08 00 10 00  01 00 fb 3d 03 3e fb 3e  03 3f
             ^ 
../tt_metal/impl/debug/dprint_server.cpp:219:29: runtime error: member access within misaligned address 0x51100020098e for type 'TileSliceHostDev<0>', which requires 4 byte alignment
0x51100020098e: note: pointer points here
 00 00 17 54 40 a3  01 00 00 00 20 00 08 00  00 00 20 00 08 00 10 00  01 00 fb 3d 03 3e fb 3e  03 3f
             ^ 
../tt_metal/impl/debug/dprint_server.cpp:219:39: runtime error: member access within misaligned address 0x51100020098e for type 'TileSliceHostDev<0>', which requires 4 byte alignment
0x51100020098e: note: pointer points here
 00 00 17 54 40 a3  01 00 00 00 20 00 08 00  00 00 20 00 08 00 10 00  01 00 fb 3d 03 3e fb 3e  03 3f
             ^ 
../tt_metal/impl/debug/dprint_server.cpp:219:39: runtime error: load of misaligned address 0x51100020099a for type 'uint16_t' (aka 'unsigned short'), which requires 4 byte alignment
0x51100020099a: note: pointer points here
 08 00  00 00 20 00 08 00 10 00  01 00 fb 3d 03 3e fb 3e  03 3f 7b 3e 83 3e 7b 3f  83 3f fb 3f 03 40
              ^ 
../tt_metal/impl/debug/dprint_server.cpp:210:57: runtime error: member access within misaligned address 0x51100020098e for type 'TileSliceHostDev<0>', which requires 4 byte alignment
0x51100020098e: note: pointer points here
 00 00 17 54 40 a3  01 00 00 00 20 00 08 00  00 00 20 00 08 00 10 00  01 00 fb 3d 03 3e fb 3e  03 3f
             ^ 
../tt_metal/impl/debug/dprint_server.cpp:232:21: runtime error: member access within misaligned address 0x51100020098e for type 'TileSliceHostDev<0>', which requires 4 byte alignment
0x51100020098e: note: pointer points here
 00 00 17 54 40 a3  01 00 00 00 20 00 08 00  00 00 20 00 08 00 10 00  01 00 fb 3d 03 3e fb 3e  03 3f
             ^ 
../tt_metal/impl/debug/dprint_server.cpp:209:53: runtime error: member access within misaligned address 0x51100020098e for type 'TileSliceHostDev<0>', which requires 4 byte alignment
0x51100020098e: note: pointer points here
 00 00 17 54 40 a3  01 00 00 00 20 00 08 00  00 00 20 00 08 00 10 00  01 00 fb 3d 03 3e fb 3e  03 3f
             ^ 
../tt_metal/impl/debug/dprint_server.cpp:209:53: runtime error: load of misaligned address 0x511000200996 for type 'uint16_t' (aka 'unsigned short'), which requires 4 byte alignment
0x511000200996: note: pointer points here
 00 00 20 00 08 00  00 00 20 00 08 00 10 00  01 00 fb 3d 03 3e fb 3e  03 3f 7b 3e 83 3e 7b 3f  83 3f
             ^ 
../tt_metal/impl/debug/dprint_server.cpp:804:30: runtime error: load of misaligned address 0x511000200a3a for type 'uint32_t' (aka 'unsigned int'), which requires 4 byte alignment
0x511000200a3a: note: pointer points here
 c7 3f  0d 04 01 00 00 00 00 12  01 00 10 01 05 0b 04 d0  0f 49 40 00 00 00 00 00  00 00 00 00 00 00
              ^ 
../tt_metal/impl/debug/dprint_server.cpp:790:49: runtime error: load of misaligned address 0x511000200b11 for type 'uint16_t' (aka 'unsigned short'), which requires 2 byte alignment
0x511000200b11: note: pointer points here
 01 40 0f  02 fb 3d 01 01 00 03 01  65 04 02 2b 02 05 04 40  e2 01 00 06 08 15 e7 cc  1f 02 00 00 00
              ^ 
../tt_metal/impl/debug/dprint_server.cpp:757:31: runtime error: load of misaligned address 0x511000200b1b for type 'uint16_t' (aka 'unsigned short'), which requires 2 byte alignment
0x511000200b1b: note: pointer points here
 01  65 04 02 2b 02 05 04 40  e2 01 00 06 08 15 e7 cc  1f 02 00 00 00 01 01 00  07 01 ef 08 02 a9 fe
              ^ 
../tt_metal/impl/debug/dprint_server.cpp:774:31: runtime error: load of misaligned address 0x511000200b35 for type 'int16_t' (aka 'short'), which requires 2 byte alignment
0x511000200b35: note: pointer points here
 01 ef 08 02 a9 fe 09  04 64 52 ff ff 0a 08 eb  40 9e ce fe ff ff ff 01  01 00 00 22 53 45 54 50  52
             ^ 
../tt_metal/impl/debug/dprint_server.cpp:782:31: runtime error: load of misaligned address 0x511000200b3f for type 'int64_t' (aka 'long'), which requires 8 byte alignment
0x511000200b3f: note: pointer points here
 ff ff 0a 08 eb  40 9e ce fe ff ff ff 01  01 00 00 22 53 45 54 50  52 45 43 49 53 49 4f 4e  2f 46 49
             ^ 
```

## Alloc-dealloc-mismatch

```
=================================================================
==392180==ERROR: AddressSanitizer: alloc-dealloc-mismatch (operator new vs free) on 0x5190001aef80
                   Test | INFO     | Finished running test on device 0.
                  Metal | INFO     | Closing device 0
                  Metal | INFO     | DPRINT Server dettached device 0
    #0 0x55d6f0820b36 in free (/home/ubuntu/dev/tt-metal/build/test/tt_metal/unit_tests_fast_dispatch+0x90ab36) (BuildId: 1b8ebef7e34862d2)
    #1 0x7f225a06b154 in std::range_error::~range_error() (/lib/x86_64-linux-gnu/libc++abi.so.1+0x25154) (BuildId: 6fcc95b8f2c3f9df0561e5fe1138b2985acf451f)
    #2 0x7f225a06d3d1 in __cxa_end_catch (/lib/x86_64-linux-gnu/libc++abi.so.1+0x273d1) (BuildId: 6fcc95b8f2c3f9df0561e5fe1138b2985acf451f)
    #3 0x7f225b1d1453 in (anonymous namespace)::DebugPrintServerContext::PollPrintData(unsigned int) /home/ubuntu/dev/tt-metal/build/../tt_metal/impl/debug/dprint_server.cpp:913:25
    #4 0x7f225b1d1453 in (anonymous namespace)::DebugPrintServerContext::DebugPrintServerContext()::$_0::operator()() const /home/ubuntu/dev/tt-metal/build/../tt_metal/impl/debug/dprint_server.cpp:366:29
    #5 0x7f225b1d1453 in decltype(std::declval<(anonymous namespace)::DebugPrintServerContext::DebugPrintServerContext()::$_0>()()) std::__1::__invoke[abi:ue170006]<(anonymous namespace)::DebugPrintServerContext::DebugPrintServerContext()::$_0>((anonymous namespace)::DebugPrintServerContext::DebugPrintServerContext()::$_0&&) /usr/lib/llvm-17/bin/../include/c++/v1/__type_traits/invoke.h:340:25
    #6 0x7f225b1d1453 in void std::__1::__thread_execute[abi:ue170006]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, (anonymous namespace)::DebugPrintServerContext::DebugPrintServerContext()::$_0>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, (anonymous namespace)::DebugPrintServerContext::DebugPrintServerContext()::$_0>&, std::__1::__tuple_indices<>) /usr/lib/llvm-17/bin/../include/c++/v1/__thread/thread.h:221:5
    #7 0x7f225b1d1453 in void* std::__1::__thread_proxy[abi:ue170006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, (anonymous namespace)::DebugPrintServerContext::DebugPrintServerContext()::$_0>>(void*) /usr/lib/llvm-17/bin/../include/c++/v1/__thread/thread.h:232:5
    #8 0x55d6f081eafa in asan_thread_start(void*) crtstuff.c
    #9 0x7f225a01d608 in start_thread /build/glibc-LcI20x/glibc-2.31/nptl/pthread_create.c:477:8
    #10 0x7f2259ae7352 in __clone /build/glibc-LcI20x/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95

0x5190001aef80 is located 0 bytes inside of 917-byte region [0x5190001aef80,0x5190001af315)
allocated by thread T228 here:
    #0 0x55d6f085d8cd in operator new(unsigned long) (/home/ubuntu/dev/tt-metal/build/test/tt_metal/unit_tests_fast_dispatch+0x9478cd) (BuildId: 1b8ebef7e34862d2)
    #1 0x7f225a0d119d in std::runtime_error::runtime_error(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) (/lib/x86_64-linux-gnu/libc++.so.1+0x5419d) (BuildId: 94ad47568b00dbdffade4d2fb445e9eef46bbe0f)
    #2 0x7f225b1d76c6 in (anonymous namespace)::DebugPrintServerContext::PeekOneHartNonBlocking(tt::tt_metal::Device*, tt::umd::xy_pair const&, int, bool) /home/ubuntu/dev/tt-metal/build/../tt_metal/impl/debug/dprint_server.cpp:661:17
    #3 0x7f225b1d104d in (anonymous namespace)::DebugPrintServerContext::PollPrintData(unsigned int) /home/ubuntu/dev/tt-metal/build/../tt_metal/impl/debug/dprint_server.cpp:895:51
    #4 0x7f225b1d104d in (anonymous namespace)::DebugPrintServerContext::DebugPrintServerContext()::$_0::operator()() const /home/ubuntu/dev/tt-metal/build/../tt_metal/impl/debug/dprint_server.cpp:366:29
    #5 0x7f225b1d104d in decltype(std::declval<(anonymous namespace)::DebugPrintServerContext::DebugPrintServerContext()::$_0>()()) std::__1::__invoke[abi:ue170006]<(anonymous namespace)::DebugPrintServerContext::DebugPrintServerContext()::$_0>((anonymous namespace)::DebugPrintServerContext::DebugPrintServerContext()::$_0&&) /usr/lib/llvm-17/bin/../include/c++/v1/__type_traits/invoke.h:340:25
    #6 0x7f225b1d104d in void std::__1::__thread_execute[abi:ue170006]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, (anonymous namespace)::DebugPrintServerContext::DebugPrintServerContext()::$_0>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, (anonymous namespace)::DebugPrintServerContext::DebugPrintServerContext()::$_0>&, std::__1::__tuple_indices<>) /usr/lib/llvm-17/bin/../include/c++/v1/__thread/thread.h:221:5
    #7 0x7f225b1d104d in void* std::__1::__thread_proxy[abi:ue170006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, (anonymous namespace)::DebugPrintServerContext::DebugPrintServerContext()::$_0>>(void*) /usr/lib/llvm-17/bin/../include/c++/v1/__thread/thread.h:232:5
    #8 0x55d6f081eafa in asan_thread_start(void*) crtstuff.c

Thread T228 created by T0 here:
    #0 0x55d6f080699d in pthread_create (/home/ubuntu/dev/tt-metal/build/test/tt_metal/unit_tests_fast_dispatch+0x8f099d) (BuildId: 1b8ebef7e34862d2)
    #1 0x7f225b1c8e37 in std::__1::__libcpp_thread_create[abi:ue170006](unsigned long*, void* (*)(void*), void*) /usr/lib/llvm-17/bin/../include/c++/v1/__threading_support:371:10
    #2 0x7f225b1c8e37 in std::__1::thread::thread<(anonymous namespace)::DebugPrintServerContext::DebugPrintServerContext()::$_0, void>((anonymous namespace)::DebugPrintServerContext::DebugPrintServerContext()::$_0&&) /usr/lib/llvm-17/bin/../include/c++/v1/__thread/thread.h:248:16
    #3 0x7f225b1c8e37 in (anonymous namespace)::DebugPrintServerContext::DebugPrintServerContext() /home/ubuntu/dev/tt-metal/build/../tt_metal/impl/debug/dprint_server.cpp:365:32
    #4 0x7f225b1c8e37 in tt::DprintServerAttach(tt::tt_metal::Device*) /home/ubuntu/dev/tt-metal/build/../tt_metal/impl/debug/dprint_server.cpp:953:44
    #5 0x7f225af98bec in tt::DevicePool::initialize_device(tt::tt_metal::Device*) const /home/ubuntu/dev/tt-metal/build/../tt_metal/impl/device/device_pool.cpp:109:5
    #6 0x7f225af9bdf3 in tt::DevicePool::init_firmware_on_active_devices() const /home/ubuntu/dev/tt-metal/build/../tt_metal/impl/device/device_pool.cpp:223:15
    #7 0x55d6f086a95e in tt::DevicePool::initialize(std::__1::vector<int, std::__1::allocator<int>>, unsigned char, unsigned long, std::__1::vector<unsigned int, std::__1::allocator<unsigned int>> const&, bool) /home/ubuntu/dev/tt-metal/build/../tt_metal/impl/device/device_pool.hpp
    #8 0x55d6f090a054 in CommonFixture::SetUp() /home/ubuntu/dev/tt-metal/build/../tests/tt_metal/tt_metal/unit_tests_common/common/common_fixture.hpp:90:9
    #9 0x55d6f09de55f in DPrintFixture::SetUp() /home/ubuntu/dev/tt-metal/build/../tests/tt_metal/tt_metal/unit_tests_common/common/dprint_fixture.hpp:57:24
    #10 0x7f2259ff709a in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/ubuntu/dev/tt-metal/build/lib/libgtest.so.1.13.0+0xd509a) (BuildId: 468e9d4358c19f0b)
    #11 0x7f2259fca109 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (/home/ubuntu/dev/tt-metal/build/lib/libgtest.so.1.13.0+0xa8109) (BuildId: 468e9d4358c19f0b)
    #12 0x7f2259fad41b in testing::Test::Run() (/home/ubuntu/dev/tt-metal/build/lib/libgtest.so.1.13.0+0x8b41b) (BuildId: 468e9d4358c19f0b)
    #13 0x7f2259fadea1 in testing::TestInfo::Run() (/home/ubuntu/dev/tt-metal/build/lib/libgtest.so.1.13.0+0x8bea1) (BuildId: 468e9d4358c19f0b)
    #14 0x7f2259fae5ac in testing::TestSuite::Run() (/home/ubuntu/dev/tt-metal/build/lib/libgtest.so.1.13.0+0x8c5ac) (BuildId: 468e9d4358c19f0b)
    #15 0x7f2259fbc62e in testing::internal::UnitTestImpl::RunAllTests() (/home/ubuntu/dev/tt-metal/build/lib/libgtest.so.1.13.0+0x9a62e) (BuildId: 468e9d4358c19f0b)
    #16 0x7f2259ffd90a in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (/home/ubuntu/dev/tt-metal/build/lib/libgtest.so.1.13.0+0xdb90a) (BuildId: 468e9d4358c19f0b)
    #17 0x7f2259fcc479 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (/home/ubuntu/dev/tt-metal/build/lib/libgtest.so.1.13.0+0xaa479) (BuildId: 468e9d4358c19f0b)
    #18 0x7f2259fbc1d7 in testing::UnitTest::Run() (/home/ubuntu/dev/tt-metal/build/lib/libgtest.so.1.13.0+0x9a1d7) (BuildId: 468e9d4358c19f0b)
    #19 0x7f225a012950 in RUN_ALL_TESTS() (/home/ubuntu/dev/tt-metal/build/lib/libgtest_main.so.1.13.0+0x1950) (BuildId: f0e7f51bc7a32715)
    #20 0x7f225a01292c in main (/home/ubuntu/dev/tt-metal/build/lib/libgtest_main.so.1.13.0+0x192c) (BuildId: f0e7f51bc7a32715)
    #21 0x7f22599ec082 in __libc_start_main /build/glibc-LcI20x/glibc-2.31/csu/../csu/libc-start.c:308:16

SUMMARY: AddressSanitizer: alloc-dealloc-mismatch (/home/ubuntu/dev/tt-metal/build/test/tt_metal/unit_tests_fast_dispatch+0x90ab36) (BuildId: 1b8ebef7e34862d2) in free
```

**Comment by yan-zaretskiy** [comment]
The alloc-dealloc-mismatch is a false-positive: https://github.com/llvm/llvm-project/issues/59432#issuecomment-1988788696

**Comment by ihamer-tt** [comment]
To reproduce the Misaligned address loads, add this to the top of CMakeLists.txt:
```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsanitize=address,undefined -fno-omit-frame-pointer")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -fsanitize=address,undefined")
```
Then run with:
```
ASAN_OPTIONS="alloc_dealloc_mismatch=0 detect_container_overflow=0" ./build/test/tt_metal/unit_tests_fast_dispatch --gtest_filter="*DPrint*"
```
