### ISSUE TITLE
[Bug Report] Getting __name__ from ttnn operations

### ISSUE THREAD

**Issue by kevinwuTT** [tenstorrent/tt-metal#9681]
**Describe the bug**
When manipulating ttnn operations in Pytorch FX Graphs, the `__name__` attribute is referenced: https://github.com/pytorch/pytorch/blob/v2.2.1/torch/fx/graph.py#L1259. However, this currently returns errors because the attribute is not found.

This is a dependency for [pytorch2.0_ttnn](https://github.com/tenstorrent-metal/pytorch2.0_ttnn) because Pytorch FX Graphs are used extensively.

**To Reproduce**
With default `enable_fast_runtime_mode: True`
```
python
>>> import ttnn
>>> ttnn.add.__name__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'ttnn._ttnn.operations.binary.add_t' object has no attribute '__name__'    
```

With fast runtime mode disabled
```
TTNN_CONFIG_OVERRIDES='{"enable_fast_runtime_mode": false}' python
>>> import ttnn
>>> ttnn.add.__name__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Operation' object has no attribute '__name__'
```

**Expected behavior**
Both should return a string of the operator name. For example, `ttnn.add.__name__` should return "ttnn.add" or something equivalent.

- OS: Ubuntu 20.04
- Version of software (eg. commit): a728de2693cc68c5fe56b47f21217ccb421b5609

**Comment by kevinwuTT** [comment]
This is solved with https://github.com/tenstorrent/tt-metal/commit/c3042ac99e8cb1ad45b09f6bec1eda3c5b6656d9!
